import { createGameHubClient } from '@gamehub/web-game-sdk';
const gamehub=createGameHubClient();
const $=id=>document.getElementById(id); let mode,room,matchId;
const log=value=>{$('log').textContent=`${new Date().toLocaleTimeString()} ${value}\n${$('log').textContent}`;};
gamehub.on('multiplayer.status',({status})=>{$('connection').textContent=`连接：${status}`;});
gamehub.on('multiplayer.room',value=>{room=value;log(`房间 ${value.id} · ${value.status}`);});
gamehub.on('multiplayer.match.started',value=>{matchId=value.id;$('match').hidden=false;gamehub.multiplayer.matches.subscribe(matchId,0);});
gamehub.on('multiplayer.match',({match,snapshot})=>{matchId=match.id;$('match').hidden=false;$('state').textContent=JSON.stringify(snapshot,null,2);});
gamehub.on('multiplayer.match.event',({event})=>{log(`权威事件 ${event.type}`);});
gamehub.on('multiplayer.match.terminal',value=>{log(`终局：${JSON.stringify(value)}`);});
gamehub.on('multiplayer.error',error=>{log(`拒绝：${error.code} ${error.message}`);});
await gamehub.connect(); await gamehub.getPlayer(); [mode]=await gamehub.multiplayer.listModes(); await gamehub.multiplayer.connect(); $('connection').textContent='已连接';
$('create').onclick=async()=>{room=await gamehub.multiplayer.rooms.create({modeId:mode.id,visibility:'invite',capacity:2});$('room-id').value=room.id;await gamehub.multiplayer.rooms.subscribe(room.id);};
$('join').onclick=async()=>{room=await gamehub.multiplayer.rooms.join($('room-id').value,mode.id,$('join-code').value||null);await gamehub.multiplayer.rooms.subscribe(room.id);};
$('ready').onclick=()=>gamehub.multiplayer.rooms.ready(room.id,true);
$('start').onclick=async()=>{const match=await gamehub.multiplayer.rooms.start(room.id);matchId=match.id;await gamehub.multiplayer.matches.subscribe(matchId,0);};
$('score').onclick=()=>gamehub.multiplayer.matches.command(matchId,{type:'score',value:$('value').value});
$('resign').onclick=()=>gamehub.multiplayer.matches.resign(matchId);
addEventListener('pagehide',()=>gamehub.close());
