import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createCloudSaveLibrary} from './cloud-save-library.mjs';
const friendly=error=>({AUTH_REQUIRED:'请先登录，再打开云端存档。',SAVE_CONFLICT:'云端已有更新，本次没有覆盖。请取消预览、刷新历史后重新选择。',SAVE_HISTORY_UNAVAILABLE:'这一版本的正文已过保留期，无法下载或恢复。',SAVE_RESTORE_NOT_ALLOWED:'当前游戏版本尚未获准恢复这份存档，你仍可导出备份。',SAVE_POLICY_NOT_ACTIVE:'该游戏已停止写入云端存档，你仍可导出备份。',SAVE_RELEASE_INCOMPATIBLE:'当前游戏版本无法读取已有存档，恢复已停止。',SAVE_SCHEMA_UNSUPPORTED:'所选历史不兼容当前游戏版本，恢复已停止。',SAVE_RATE_LIMITED:'操作过于频繁，请稍后重试。'}[error.code]??error.message??'请求失败，请重试。');
const date=value=>new Date(value).toLocaleString('zh-CN');
export default function CloudSaveLibrary({api,go}) {
  const manager=useMemo(()=>createCloudSaveLibrary({api}),[api]);
  const [page,setPage]=useState({items:[],nextAfterSlotId:null}),[history,setHistory]=useState(null),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false);
  const [preview,setPreview]=useState(null),[confirmed,setConfirmed]=useState(false),[exported,setExported]=useState(null);
  const mounted=useRef(true),lock=useRef(false),previewFocus=useRef(null),exportFocus=useRef(null);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;manager.cancel();};},[manager]);
  const run=async task=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await task();}catch(error){if(mounted.current)setMessage(friendly(error));}finally{lock.current=false;if(mounted.current)setBusy(false);}};
  const load=async more=>{const {data}=await api.listSaveLibrary(more?page.nextAfterSlotId:undefined);if(mounted.current){setPage(old=>({...data,items:more?[...old.items,...data.items]:data.items}));setLoaded(true);}};
  useEffect(()=>{run(()=>load(false));},[api]);
  useEffect(()=>{if(preview)previewFocus.current?.focus();},[preview]);
  useEffect(()=>{if(exported)exportFocus.current?.focus();},[exported]);
  const openHistory=(slotId,more=false)=>run(async()=>{const {data}=await api.getSaveLibraryHistory(slotId,more?history.nextBeforeRevision:undefined);if(mounted.current){setHistory(old=>({...data,items:more?[...old.items,...data.items]:data.items}));setExported(null);}});
  const prepare=revision=>run(async()=>{const result=await manager.prepareRestore(history.slot.slotId,revision.revisionId);if(mounted.current){setPreview({revision,current:result.current});setConfirmed(false);setExported(null);}});
  const restore=()=>run(async()=>{const result=await manager.restore();if(mounted.current){setPreview(null);setHistory(null);setMessage('已恢复为新版本 #'+result.revision+'。下次打开游戏会读取该版本；如设备有未同步进度，请先比较冲突。');const {data}=await api.listSaveLibrary();if(mounted.current)setPage(data);}});
  const exportRevision=revision=>run(async()=>{const text=await manager.exportRevision(history.slot,revision);if(mounted.current)setExported({text,name:history.slot.slot+'-r'+revision.revision+'.gamehub-save.json'});});
  const downloadUrl=useMemo(()=>exported?URL.createObjectURL(new Blob([exported.text],{type:'application/json'})):null,[exported]);
  useEffect(()=>()=>{if(downloadUrl)URL.revokeObjectURL(downloadUrl);},[downloadUrl]);
  return <main className="page cloud-save-library"><button className="back-link" onClick={()=>go('/account')}>← 返回个人设置</button><header className="settings-heading"><div><span className="kicker">CLOUD SAVES</span><h1>云端存档</h1><p>查看历史、导出备份，或把保留的版本恢复为新的进度。</p></div></header>
    <p className="cloud-save-note">恢复前请关闭其他正在运行的游戏窗口。未同步的本机进度会在下次进入游戏时要求比较；恢复不会清除它们。历史正文受保留期限和空间限制，重要进度请导出备份。</p>
    {message&&<p role="status" className="cloud-save-note">{message}</p>}
    {!preview&&<div className="cloud-save-actions"><button disabled={busy} onClick={()=>run(async()=>{setHistory(null);setExported(null);await load(false);})}>刷新存档</button><button onClick={()=>go('/account')}>账号设置</button></div>}
    {busy&&<p role="status">正在处理…</p>}
    {!history&&!preview&&<section aria-label="云端存档列表">{loaded&&!page.items.length&&<p>当前账号还没有云端存档。</p>}{page.items.map(slot=><article className="settings-panel cloud-save-row" key={slot.slotId}><div><h2>{slot.workTitle}</h2><p>{slot.channel==='production'?'正式版':'作者预览'} · {slot.namespace} / {slot.slot}</p><small>版本 #{slot.revision} · {slot.deleted?'已删除，可查看保留的历史':slot.bytes+' 字节'} · {date(slot.updatedAt)}</small></div><button disabled={busy} onClick={()=>openHistory(slot.slotId)}>查看历史</button></article>)}{page.nextAfterSlotId&&<button disabled={busy} onClick={()=>run(()=>load(true))}>加载更多存档</button>}</section>}
    {exported&&<section className="settings-panel"><h2 ref={exportFocus} tabIndex={-1}>备份已校验</h2><p>保存文件，或复制完整备份文本。可在游戏的“存档管理”中导入。</p><a href={downloadUrl} download={exported.name}>下载备份文件</a><label className="cloud-save-export">完整备份文本<textarea readOnly rows={8} value={exported.text} onFocus={event=>event.target.select()}/></label></section>}
    {history&&!preview&&<section className="settings-panel"><div className="cloud-save-row"><div><h2>{history.slot.workTitle} · {history.slot.slot}</h2><p>当前云端版本 #{history.slot.revision}{history.slot.deleted?'（已删除）':''}</p></div><button disabled={busy} onClick={()=>{setHistory(null);setExported(null);}}>返回列表</button></div><ol className="cloud-save-history">{history.items.map(item=><li key={item.revisionId}><div><strong>版本 #{item.revision}{item.revisionId===history.slot.revisionId?' · 当前':''}</strong><p>{date(item.updatedAt)} · {item.bytes} 字节{item.restoredFromRevisionId?' · 历史恢复':''}</p><small>{item.deleted?'删除记录':item.payloadAvailable?'正文可用 · 格式 '+item.schemaVersion:'正文已过保留期'}</small></div><div className="cloud-save-actions"><button disabled={busy||!item.payloadAvailable||item.deleted} onClick={()=>exportRevision(item)}>导出备份</button><button disabled={busy||!item.payloadAvailable||item.deleted||item.revisionId===history.slot.revisionId} onClick={()=>prepare(item)}>预览恢复</button></div></li>)}</ol>{history.nextBeforeRevision&&<button disabled={busy} onClick={()=>openHistory(history.slot.slotId,true)}>更早的历史</button>}</section>}
    {preview&&<section className="settings-panel cloud-save-preview" aria-labelledby="cloud-restore-title"><h2 id="cloud-restore-title" ref={previewFocus} tabIndex={-1}>确认恢复预览</h2><p>把版本 #{preview.revision.revision} 的进度恢复为新版本。当前云端是 #{preview.current.revision}，操作时若发生更新，将停止恢复。</p><dl><dt>存档</dt><dd>{preview.current.workTitle} / {preview.current.namespace} / {preview.current.slot}</dd><dt>历史时间</dt><dd>{date(preview.revision.updatedAt)}</dd><dt>正文</dt><dd>{preview.revision.bytes} 字节 · 格式 {preview.revision.schemaVersion}</dd><dt>SHA-256</dt><dd className="cloud-save-digest">{preview.revision.sha256}</dd></dl><p>当前云端进度将进入历史，受相同保留规则约束；需要长期保留时，请先取消并导出当前版本。</p><label><input type="checkbox" checked={confirmed} disabled={busy} onChange={event=>setConfirmed(event.target.checked)}/> 我已关闭其他游戏窗口，并确认所选历史版本。</label><div className="cloud-save-actions"><button disabled={busy||!confirmed} onClick={restore}>确认恢复 / 重试</button><button disabled={busy} onClick={()=>{manager.cancel();setPreview(null);setConfirmed(false);}}>取消预览</button></div></section>}

  </main>;
}
