import React,{useEffect,useState} from 'react';
import {EventCard} from './CommunityEvents.jsx';
import {PartyCard} from './CommunityParties.jsx';

const demo={happening:[],projects:[],rankingNote:'按即将发生、仍可参与和最近更新排序；点赞数不会单独决定推荐。'};
export default function CommunityHome({api,demo:demoMode,go,accountProfile,children}){
  const [state,setState]=useState({status:'loading',data:null});
  useEffect(()=>{let live=true;setState({status:'loading',data:null});Promise.resolve(demoMode?demo:api.communityOverview().then(result=>result.data)).then(data=>live&&setState({status:'ready',data})).catch(error=>live&&setState({status:'error',data:null,error}));return()=>{live=false;};},[api,demoMode,accountProfile?.id]);
  const data=state.data||demo;
  return <section className="community-dashboard"><header className="community-dashboard__intro"><div><span className="kicker">TOGETHER, NOW</span><h2>找到人，也找到现在能做的事。</h2><p>社区把动态、持续项目、某个时间发生的活动和一局游戏放在同一个可信的参与入口。</p></div><aside>{accountProfile?<><span>我的下一步</span><strong>查看已报名、已加入和待处理事项</strong><button onClick={()=>go('/community/me')}>打开参与收件箱 →</button></>:<><span>从这里开始</span><strong>登录后可以报名、申请加入和组队</strong><button onClick={()=>go('/account')}>登录 GameHub →</button></>}</aside></header><section className="community-dashboard__section"><div className="community-dashboard__heading"><div><span className="kicker">HAPPENING SOON</span><h2>正在发生</h2></div><button onClick={()=>go('/community/events')}>查看全部 →</button></div>{state.status==='loading'?<div className="community-activity-list"><i className="community-activity-skeleton"/><i className="community-activity-skeleton"/></div>:data.happening.length?<div className="community-dashboard__happening">{data.happening.slice(0,3).map(item=>item.kind==='event'?<EventCard key={`event-${item.id}`} event={item} go={go}/>:<PartyCard key={`party-${item.id}`} party={item} go={go}/>)}</div>:<div className="community-dashboard__empty"><span aria-hidden="true">◫</span><div><strong>暂时没有临近的活动或队伍</strong><p>这里不会填充虚假热闹。你可以发起一个目标和时间都明确的邀请。</p></div><button onClick={()=>go('/community/events/new')}>组织活动</button></div>}</section><section className="community-dashboard__section"><div className="community-dashboard__heading"><div><span className="kicker">OPEN COLLABORATION</span><h2>值得加入的项目</h2></div><button onClick={()=>go('/community/projects')}>查看全部 →</button></div>{data.projects.length?<div className="community-dashboard__projects">{data.projects.map(project=><button key={project.id} onClick={()=>go(`/community/projects/${project.id}`)}><span>{project.status==='recruiting'?'招募中':'进行中'}</span><strong>{project.title}</strong><p>{project.summary}</p><small>{project.memberCount} 位成员 · {project.openTaskCount} 个开放任务</small></button>)}</div>:<div className="community-dashboard__empty is-small"><span aria-hidden="true">↗</span><div><strong>还没有开放项目</strong><p>也可以先从作者公开的独立任务开始。</p></div><button onClick={()=>go('/community/projects')}>去一起做</button></div>}<p className="community-ranking-note">{data.rankingNote}</p></section><section className="community-dashboard__section is-feed"><div className="community-dashboard__heading"><div><span className="kicker">LATEST STORIES</span><h2>最新动态</h2></div><button onClick={()=>go('/community/feed')}>进入动态 →</button></div>{children}</section></section>;
}
