import React,{useEffect,useState} from 'react';

const local=value=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
export default function CommunityParticipation({api,demo,go,accountProfile}){
  const [state,setState]=useState({status:'loading',data:null}),[tab,setTab]=useState('next');
  useEffect(()=>{let live=true;if(!accountProfile){setState({status:'guest',data:null});return;}setState({status:'loading',data:null});Promise.resolve(demo?{events:[],parties:[],projects:[],notifications:[]}:(api.communityParticipation().then(result=>result.data))).then(data=>live&&setState({status:'ready',data})).catch(error=>live&&setState({status:'error',data:null,error}));return()=>{live=false;};},[api,demo,accountProfile?.id]);
  if(state.status==='guest')return <section className="community-participation-empty"><span>◇</span><h2>把你的下一步放在一起</h2><p>登录后，这里会显示项目申请、即将开始的活动、已经加入的队伍和历史记录。</p><button className="button button--primary" onClick={()=>go('/account')}>登录后查看</button></section>;
  if(state.status==='loading')return <div className="community-activity-skeleton"/>;if(state.status==='error')return <p className="community-project-state is-error">{state.error?.message||'参与记录暂时无法读取。'}</p>;
  const data=state.data,activeEvents=data.events.filter(item=>item.state==='scheduled'),activeParties=data.parties.filter(item=>!['ended','cancelled'].includes(item.state)),activeProjects=data.projects.filter(item=>!['completed','archived','cancelled'].includes(item.status));
  const collections=tab==='next'?[...activeEvents.map(item=>({...item,kind:'event'})),...activeParties.map(item=>({...item,kind:'party'})),...activeProjects.map(item=>({...item,kind:'project'}))]:tab==='projects'?data.projects.map(item=>({...item,kind:'project'})):tab==='events'?data.events.map(item=>({...item,kind:'event'})):data.parties.map(item=>({...item,kind:'party'}));
  const dismiss=async notification=>{if(!demo)await api.communityParticipationNotificationRead(notification.id);setState(current=>({...current,data:{...current.data,notifications:current.data.notifications.filter(item=>item.id!==notification.id)}}));};
  return <section className="community-participation"><header className="community-section-heading"><div><span className="kicker">MY PARTICIPATION</span><h2>我的参与</h2><p>先显示需要你关注的事情，历史内容安静地留在各分类中。</p></div></header>{!!data.notifications?.length&&<section className="community-reminders" aria-label="参与提醒"><span className="kicker">REMINDERS</span>{data.notifications.map(notification=><article key={notification.id}><span aria-hidden="true">!</span><p>{notification.message}</p><button onClick={()=>go(`/community/${notification.subjectKind==='event'?'events':'parties'}/${notification.subjectId}`)}>查看</button><button aria-label="标记已读" onClick={()=>dismiss(notification)}>×</button></article>)}</section>}<nav className="community-personal-nav"><button className={tab==='next'?'is-active':''} onClick={()=>setTab('next')}>需要我处理</button><button className={tab==='projects'?'is-active':''} onClick={()=>setTab('projects')}>项目</button><button className={tab==='events'?'is-active':''} onClick={()=>setTab('events')}>活动</button><button className={tab==='parties'?'is-active':''} onClick={()=>setTab('parties')}>组队</button><button onClick={()=>go('/community/mine')}>分享</button><button onClick={()=>go('/community/bookmarks')}>收藏</button></nav><div className="community-inbox">{collections.map(item=><article key={`${item.kind}-${item.id}`}><span>{item.kind==='project'?'↗':item.kind==='event'?'◫':'◉'}</span><div><small>{item.kind==='project'?'协作项目':item.kind==='event'?'活动':'游戏组队'}</small><strong>{item.title}</strong><p>{item.kind==='project'?`${item.memberCount} 位成员 · ${item.openTaskCount} 个开放任务`:item.kind==='event'?`${local(item.startsAt)} · ${item.myAttendance==='registered'?'已报名':'我发起'}`:`${local(item.startsAt)} · ${item.memberCount}/${item.capacity} 人`}</p></div><button onClick={()=>go(`/community/${item.kind==='project'?'projects':item.kind==='event'?'events':'parties'}/${item.id}`)}>查看 →</button></article>)}</div>{!collections.length&&<p className="community-project-state">这里暂时没有需要你处理的事项。</p>}</section>;
}
