import React,{useEffect,useState} from 'react';

const stateLabels={recruiting:'招募中',full:'已满员',ready:'已准备',playing:'游戏中',ended:'已结束',cancelled:'已取消'};
const localTime=value=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const toLocalInput=date=>new Date(new Date(date-Date.now()%60000).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
const demoParty={id:'demo-party',title:'HexGL 新手友好竞速',modeLabel:'两局练习 + 一局计时',note:'第一次玩也欢迎，开局前会先说明操作和房间规则。',startsAt:new Date(Date.now()+2*3_600_000).toISOString(),capacity:4,state:'recruiting',roomMode:'gamehub',roomId:null,externalInstructions:null,host:{id:'demo-host',displayName:'赛道猫',handle:'track-cat'},work:{id:'demo-work',title:'HexGL'},gameMode:{id:'demo-mode',name:'竞速'},memberCount:2,readyCount:1,isHost:false,myMembership:null,version:1,members:[{id:'demo-host',displayName:'赛道猫',handle:'track-cat',ready:true},{id:'demo-two',displayName:'紫色玩家',handle:'violet',ready:false}]};
function useRemote(read,deps){const [state,setState]=useState({status:'loading',data:null}),[revision,setRevision]=useState(0);useEffect(()=>{let live=true;setState(current=>({...current,status:'loading'}));Promise.resolve().then(read).then(data=>live&&setState({status:'ready',data})).catch(error=>live&&setState({status:'error',data:null,error}));return()=>{live=false;};},[...deps,revision]);return[state,()=>setRevision(value=>value+1)];}
const Button=({secondary=false,children,...props})=><button type={props.onClick?'button':'submit'} className={`button button--${secondary?'secondary':'primary'}`} {...props}><span>{children}</span></button>;
const Seats=({count,capacity})=><span className="community-party-seats" aria-label={`${count}/${capacity} 人`}>{Array.from({length:capacity},(_,index)=><i key={index} className={index<count?'is-filled':''}/>)}</span>;

function PartyForm({api,onCreated,onCancel}){
  const [works,setWorks]=useState([]),[modes,setModes]=useState([]),[form,setForm]=useState({title:'',workId:'',modeId:'',modeLabel:'休闲组队',note:'欢迎不同水平的玩家，开局前会先确认规则。',startsAt:toLocalInput(Date.now()+3_600_000),capacity:4,roomMode:'gamehub',externalInstructions:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let live=true;api.listWorks({limit:50,kind:'game'}).then(({data})=>live&&setWorks(data)).catch(()=>live&&setWorks([]));return()=>{live=false;};},[api]);
  useEffect(()=>{let live=true;if(!form.workId){setModes([]);return;}api.listMultiplayerModes(form.workId).then(({data})=>{if(!live)return;setModes(data);if(data.length)setForm(current=>({...current,roomMode:'gamehub',modeId:data[0].id,capacity:Math.min(4,data[0].maxPlayers),modeLabel:data[0].name}));else setForm(current=>({...current,roomMode:'external',modeId:''}));}).catch(()=>live&&setModes([]));return()=>{live=false;};},[api,form.workId]);
  const field=(key,value)=>setForm(current=>({...current,[key]:value}));
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const response=await api.communityPartyCreate({...form,startsAt:new Date(form.startsAt).toISOString(),capacity:Number(form.capacity),modeId:form.roomMode==='gamehub'?form.modeId:null,externalInstructions:form.roomMode==='external'?form.externalInstructions:null});onCreated(response.data);}catch(cause){setError(cause.message||'组队暂时无法创建。');}finally{setBusy(false);}};
  return <form className="community-activity-form" onSubmit={submit}><div className="form-grid"><label>选择游戏<select required value={form.workId} onChange={event=>field('workId',event.target.value)}><option value="">选择公开游戏</option>{works.map(work=><option key={work.id} value={work.id}>{work.title}</option>)}</select></label><label>组队标题<input required minLength="3" maxLength="100" value={form.title} onChange={event=>field('title',event.target.value)}/></label></div><div className="form-grid"><label>房间方式<select value={form.roomMode} onChange={event=>field('roomMode',event.target.value)}><option value="gamehub" disabled={!modes.length}>GameHub 房间{!modes.length?'（该游戏未接入）':''}</option><option value="external">外部组织</option></select></label>{form.roomMode==='gamehub'?<label>游戏模式<select required value={form.modeId} onChange={event=>{const mode=modes.find(item=>item.id===event.target.value);setForm(current=>({...current,modeId:event.target.value,modeLabel:mode?.name||current.modeLabel,capacity:Math.min(Number(current.capacity),mode?.maxPlayers||8)}));}}>{modes.map(mode=><option key={mode.id} value={mode.id}>{mode.name} · {mode.minPlayers}-{mode.maxPlayers} 人</option>)}</select></label>:<label>模式说明<input required minLength="2" maxLength="80" value={form.modeLabel} onChange={event=>field('modeLabel',event.target.value)}/></label>}<label>开局时间<input required type="datetime-local" value={form.startsAt} onChange={event=>field('startsAt',event.target.value)}/></label><label>人数<input required type="number" min="2" max="8" value={form.capacity} onChange={event=>field('capacity',event.target.value)}/></label></div><label>组队说明<textarea required minLength="10" maxLength="500" value={form.note} onChange={event=>field('note',event.target.value)}/></label>{form.roomMode==='external'&&<label>外部组织说明（仅队员可见）<textarea required minLength="10" maxLength="1000" value={form.externalInstructions} onChange={event=>field('externalInstructions',event.target.value)} placeholder="例如：加入后在活动页查看语音频道与房间说明。"/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="community-form-actions"><Button disabled={busy}>{busy?'创建中…':'发起组队'}</Button><Button secondary disabled={busy} onClick={onCancel}>取消</Button></div></form>;
}

export function PartyCard({party,go}){return <article className="community-party-card"><div className="community-party-cover" aria-hidden="true"><span>{party.work.title.slice(0,1)}</span><small>{party.roomMode==='gamehub'?'GAMEHUB':'EXTERNAL'}</small></div><div><header><span>{party.work.title}</span><em>{stateLabels[party.state]}</em></header><h3>{party.title}</h3><p>{party.note}</p><div className="community-party-meta"><span>{localTime(party.startsAt)}</span><span>{party.modeLabel}</span><Seats count={party.memberCount} capacity={party.capacity}/></div><footer><span>{party.host.displayName} 发起</span><button type="button" onClick={()=>go(`/community/parties/${party.id}`)}>查看队伍 →</button></footer></div></article>;}

function PartyDetail({api,demo,go,accountProfile,partyId}){
  const [state,reload]=useRemote(async()=>demo?demoParty:(await api.communityParty(partyId)).data,[api,demo,partyId,accountProfile?.id]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const run=async(action,value)=>{if(!accountProfile)return go('/account');setBusy(true);setNotice('');try{if(!demo){if(action==='join')await api.communityPartyJoin(partyId);if(action==='leave')await api.communityPartyLeave(partyId);if(action==='ready')await api.communityPartyReady(partyId,value);if(action==='start')await api.communityPartyStart(partyId);if(action==='ended'||action==='cancelled')await api.communityPartyFinish(partyId,action);}setNotice(demo?'演示模式不保存修改。':'队伍状态已更新。');reload();}catch(error){setNotice(error.message||'队伍暂时无法更新。');}finally{setBusy(false);}};
  const enter=async party=>{setBusy(true);setNotice('');try{if(party.roomMode==='external')return; if(!party.isHost)await api.joinMultiplayerRoomScoped(party.roomId,party.gameMode.id);go(`/play/${party.work.id}/room/${party.roomId}`);}catch(error){setNotice(error.message||'暂时无法进入游戏房间。');}finally{setBusy(false);}};
  if(state.status==='loading')return <div className="community-activity-skeleton"/>;if(state.status==='error')return <p className="community-project-state is-error">{state.error?.message||'组队暂时无法读取。'}</p>;
  const party=state.data,joined=party.myMembership?.state==='active',canJoin=['recruiting','full','ready'].includes(party.state)&&party.memberCount<party.capacity;
  return <section className="community-party-detail"><button className="back-link" onClick={()=>go('/community/parties')}>← 返回游戏组队</button><header className="community-activity-hero is-party"><div className="community-party-cover is-large" aria-hidden="true"><span>{party.work.title.slice(0,1)}</span></div><div><span className="kicker">{party.work.title} · {stateLabels[party.state]}</span><h1>{party.title}</h1><p>{party.note}</p><div className="community-activity-facts"><span>{localTime(party.startsAt)}</span><span>{party.modeLabel}</span><span>{party.memberCount}/{party.capacity} 人</span><span>{party.roomMode==='gamehub'?'平台托管房间':'外部组织'}</span></div></div></header>{notice&&<p className="contribution-message" role="status">{notice}</p>}<div className="community-activity-detail-grid"><main><section><h2>队伍席位</h2><Seats count={party.memberCount} capacity={party.capacity}/><div className="community-party-members">{(party.members||[]).map(member=><article key={member.id}><i>{member.displayName.slice(0,1)}</i><strong>{member.displayName}</strong><span>{member.ready?'已准备':'未准备'}</span></article>)}</div></section>{party.roomMode==='external'&&joined&&<section><h2>外部组织说明</h2><p>{party.externalInstructions}</p><small>外部组织由发起人管理，GameHub 不托管对局或验证外部平台身份。</small></section>}</main><aside><span className="kicker">YOUR SEAT</span><strong>{joined?'你已在队伍中':party.memberCount>=party.capacity?'当前已满员':'还有空位'}</strong><p>{party.roomMode==='gamehub'?'开始后会创建真实 GameHub 房间，队员进入时再占用房间席位。':'加入后才能查看外部组织说明。'}</p>{!joined&&canJoin&&<Button disabled={busy} onClick={()=>run('join')}>加入队伍</Button>}{joined&&!party.isHost&&['recruiting','full','ready'].includes(party.state)&&<><Button disabled={busy} onClick={()=>run('ready',!party.myMembership.ready)}>{party.myMembership.ready?'取消准备':'我已准备'}</Button><Button secondary disabled={busy} onClick={()=>run('leave')}>退出队伍</Button></>}{party.isHost&&['recruiting','full','ready'].includes(party.state)&&<><Button disabled={busy||party.memberCount<2||party.readyCount!==party.memberCount} onClick={()=>run('start')}>开始并创建房间</Button>{party.readyCount!==party.memberCount&&<small>所有队员确认准备后才能开始。</small>}<Button secondary disabled={busy} onClick={()=>run('cancelled')}>取消组队</Button></>}{joined&&party.state==='playing'&&party.roomMode==='gamehub'&&party.roomId&&<Button disabled={busy} onClick={()=>enter(party)}>进入游戏房间</Button>}{party.isHost&&party.state==='playing'&&<Button secondary disabled={busy} onClick={()=>run('ended')}>结束组队</Button>}</aside></div></section>;
}

export default function CommunityParties({api,demo,go,accountProfile,partyId,create=false}){const [creating,setCreating]=useState(create),[mine,setMine]=useState(false),[state,reload]=useRemote(async()=>demo?[demoParty]:(await api.communityParties(mine?{mine:true}:{})).data,[api,demo,mine,accountProfile?.id]);if(partyId)return <PartyDetail api={api} demo={demo} go={go} accountProfile={accountProfile} partyId={partyId}/>;const created=party=>{setCreating(false);reload();go(`/community/parties/${party.id}`);};return <section className="community-parties-index"><header className="community-section-heading"><div><span className="kicker">GAME PARTIES</span><h2>找人一起开一局</h2><p>先确认游戏、时间、模式和人数。支持 GameHub 房间，也诚实标记外部组织。</p></div><Button onClick={()=>accountProfile?setCreating(value=>!value):go('/account')}>{creating?'收起创建':'＋ 发起组队'}</Button></header><nav className="community-personal-nav"><button className={!mine?'is-active':''} onClick={()=>setMine(false)}>可加入</button><button className={mine?'is-active':''} onClick={()=>accountProfile?setMine(true):go('/account')}>我的队伍</button></nav>{creating&&<PartyForm api={api} onCreated={created} onCancel={()=>setCreating(false)}/>}<p className="community-ranking-note">可加入队伍优先，其次按开局时间和最近更新排序。</p>{state.status==='loading'?<div className="community-party-grid"><i className="community-activity-skeleton"/><i className="community-activity-skeleton"/></div>:state.status==='error'?<p className="community-project-state is-error">{state.error?.message||'组队暂时无法读取。'}</p>:<div className="community-party-grid">{state.data.map(party=><PartyCard key={party.id} party={party} go={go}/>)}</div>}{state.status==='ready'&&!state.data.length&&<p className="community-project-state">现在还没有可加入的队伍。选择一个游戏，发起第一队吧。</p>}</section>;}
