import React,{useEffect,useState} from 'react';

const typeLabels={meetup:'线上聚会',playtest:'试玩会',discussion:'讨论',workshop:'工作坊',project_meeting:'项目会议'};
const timingLabels={upcoming:'开放报名',soon:'即将开始',live:'进行中',ended:'已结束',cancelled:'已取消'};
const localDate=value=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',weekday:'short'}).format(new Date(value));
const localTime=value=>new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(value));
const toLocalInput=date=>{const value=new Date(date-Date.now()%60000);return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const demoEvent={id:'demo-event',title:'像素迷阵移动端试玩会',summary:'一起在手机上试玩最新版本，记录触控、横竖屏和新手引导问题。',eventType:'playtest',startsAt:new Date(Date.now()+3_600_000).toISOString(),endsAt:new Date(Date.now()+7_200_000).toISOString(),capacity:12,attendeeCount:5,state:'scheduled',timing:'upcoming',recording:false,joinWindowMinutes:60,codeOfConduct:'尊重参与者，围绕试玩体验提供具体反馈。',cancellationPolicy:'如需取消，主办人会至少提前一小时在活动页说明。',meetingUrl:null,meetingAvailable:false,host:{id:'demo-author',displayName:'像素作者',handle:'pixel-author'},project:{id:'demo-project',title:'像素迷阵移动端适配'},work:{id:'demo-work',title:'像素迷阵'},isHost:false,myAttendance:null,version:1,attendees:[]};

function useRemote(read,deps){const [state,setState]=useState({status:'loading',data:null}),[revision,setRevision]=useState(0);useEffect(()=>{let live=true;setState(current=>({...current,status:'loading'}));Promise.resolve().then(read).then(data=>live&&setState({status:'ready',data})).catch(error=>live&&setState({status:'error',data:null,error}));return()=>{live=false;};},[...deps,revision]);return[state,()=>setRevision(value=>value+1)];}
const Button=({secondary=false,children,...props})=><button type={props.onClick?'button':'submit'} className={`button button--${secondary?'secondary':'primary'}`} {...props}><span>{children}</span></button>;

function EventForm({api,onCreated,onCancel}){
  const startDefault=toLocalInput(Date.now()+24*60*60_000),endDefault=toLocalInput(Date.now()+25*60*60_000);
  const [form,setForm]=useState({title:'',summary:'',eventType:'playtest',startsAt:startDefault,endsAt:endDefault,capacity:12,meetingUrl:'',joinWindowMinutes:60,recording:false,codeOfConduct:'尊重每位参与者，不骚扰，不公开他人的私人信息。',cancellationPolicy:'如需取消，主办人会尽早在活动页说明并通知已报名成员。'}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const field=(key,value)=>setForm(current=>({...current,[key]:value}));
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const response=await api.communityEventCreate({...form,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),capacity:Number(form.capacity),joinWindowMinutes:Number(form.joinWindowMinutes),meetingUrl:form.meetingUrl||null});onCreated(response.data);}catch(cause){setError(cause.message||'活动暂时无法创建。');}finally{setBusy(false);}};
  return <form className="community-activity-form" onSubmit={submit}><div className="form-grid"><label>活动名称<input required minLength="3" maxLength="100" value={form.title} onChange={event=>field('title',event.target.value)}/></label><label>活动类型<select value={form.eventType} onChange={event=>field('eventType',event.target.value)}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><label>活动说明<textarea required minLength="10" maxLength="500" value={form.summary} onChange={event=>field('summary',event.target.value)}/></label><div className="form-grid"><label>开始时间<input required type="datetime-local" value={form.startsAt} onChange={event=>field('startsAt',event.target.value)}/></label><label>结束时间<input required type="datetime-local" value={form.endsAt} onChange={event=>field('endsAt',event.target.value)}/></label><label>人数上限<input required type="number" min="2" max="200" value={form.capacity} onChange={event=>field('capacity',event.target.value)}/></label><label>会议链接开放时间<select value={form.joinWindowMinutes} onChange={event=>field('joinWindowMinutes',event.target.value)}><option value="30">开始前 30 分钟</option><option value="60">开始前 1 小时</option><option value="180">开始前 3 小时</option><option value="1440">开始前 1 天</option></select></label></div><label>HTTPS 会议地址（可选，仅在时窗内对报名者显示）<input type="url" pattern="https://.*" value={form.meetingUrl} onChange={event=>field('meetingUrl',event.target.value)}/></label><label className="community-check"><input type="checkbox" checked={form.recording} onChange={event=>field('recording',event.target.checked)}/> 本次活动会录制</label><div className="form-grid"><label>行为规则<textarea required minLength="10" maxLength="1000" value={form.codeOfConduct} onChange={event=>field('codeOfConduct',event.target.value)}/></label><label>取消政策<textarea required minLength="10" maxLength="500" value={form.cancellationPolicy} onChange={event=>field('cancellationPolicy',event.target.value)}/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="community-form-actions"><Button disabled={busy}>{busy?'创建中…':'创建并开放报名'}</Button><Button secondary disabled={busy} onClick={onCancel}>取消</Button></div></form>;
}

export function EventCard({event,go}){const available=Math.max(0,event.capacity-event.attendeeCount);return <article className="community-event-card"><time dateTime={event.startsAt}><b>{new Date(event.startsAt).getDate()}</b><span>{new Intl.DateTimeFormat('zh-CN',{month:'short'}).format(new Date(event.startsAt))}</span></time><div><header><span>{typeLabels[event.eventType]}</span><em className={`is-${event.timing}`}>{timingLabels[event.timing]||event.state}</em></header><h3>{event.title}</h3><p>{event.summary}</p><footer><span>{localTime(event.startsAt)}</span><span>{event.attendeeCount}/{event.capacity} 人</span><strong>{available?`还剩 ${available} 个名额`:'名额已满'}</strong><button type="button" onClick={()=>go(`/community/events/${event.id}`)}>查看活动 →</button></footer></div></article>;}

function EventDetail({api,demo,go,accountProfile,eventId}){
  const [state,reload]=useRemote(async()=>demo?demoEvent:(await api.communityEvent(eventId)).data,[api,demo,eventId,accountProfile?.id]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const run=async action=>{if(!accountProfile)return go('/account');setBusy(true);setNotice('');try{if(!demo){if(action==='register')await api.communityEventRegister(eventId);else if(action==='unregister')await api.communityEventUnregister(eventId);else await api.communityEventUpdate(eventId,{expectedVersion:state.data.version,state:action});}setNotice(demo?'演示模式不保存修改。':'活动状态已更新。');reload();}catch(error){setNotice(error.message||'活动暂时无法更新。');}finally{setBusy(false);}};
  if(state.status==='loading')return <div className="community-activity-skeleton" aria-label="正在读取活动"/>;if(state.status==='error')return <p className="community-project-state is-error">{state.error?.message||'活动暂时无法读取。'}</p>;
  const event=state.data,registered=['registered','attended'].includes(event.myAttendance),open=event.state==='scheduled'&&event.timing!=='ended',full=event.attendeeCount>=event.capacity;
  return <section className="community-event-detail"><button className="back-link" type="button" onClick={()=>go('/community/events')}>← 返回活动</button><header className="community-activity-hero"><div className="community-event-date"><b>{new Date(event.startsAt).getDate()}</b><span>{new Intl.DateTimeFormat('zh-CN',{month:'long'}).format(new Date(event.startsAt))}</span></div><div><span className="kicker">{typeLabels[event.eventType]} · {timingLabels[event.timing]}</span><h1>{event.title}</h1><p>{event.summary}</p><div className="community-activity-facts"><span>{localDate(event.startsAt)} {localTime(event.startsAt)}</span><span>约 {Math.round((new Date(event.endsAt)-new Date(event.startsAt))/60000)} 分钟</span><span>{event.attendeeCount}/{event.capacity} 人</span><span>{event.recording?'会录制':'不录制'}</span></div></div></header>{notice&&<p className="contribution-message" role="status">{notice}</p>}<div className="community-activity-detail-grid"><main><section><h2>参加前须知</h2><h3>行为规则</h3><p>{event.codeOfConduct}</p><h3>取消政策</h3><p>{event.cancellationPolicy}</p></section>{event.project&&<section><h2>关联项目</h2><button className="community-context-link" onClick={()=>go(`/community/projects/${event.project.id}`)}>{event.project.title} →</button></section>}<section><h2>参与者</h2><div className="community-people-grid">{(event.attendees||[]).map(person=><button key={person.id} onClick={()=>person.handle&&go(`/u/${person.handle}`)}><i>{person.displayName.slice(0,1)}</i><span>{person.displayName}</span></button>)}</div></section></main><aside><span className="kicker">YOUR NEXT STEP</span><strong>{registered?'你已报名':full?'名额已满':'现在可以报名'}</strong><p>会议链接仅向报名者在开始前 {event.joinWindowMinutes} 分钟至结束后 2 小时显示。</p>{event.meetingAvailable&&<a className="button button--primary" href={event.meetingUrl} target="_blank" rel="noreferrer">打开会议 ↗</a>}{open&&!registered&&!full&&<Button disabled={busy} onClick={()=>run('register')}>报名参加</Button>}{registered&&!event.isHost&&open&&<Button secondary disabled={busy} onClick={()=>run('unregister')}>取消报名</Button>}{event.isHost&&event.state==='scheduled'&&<><Button secondary disabled={busy} onClick={()=>run('completed')}>标记结束</Button><Button secondary disabled={busy} onClick={()=>run('cancelled')}>取消活动</Button></>}{event.recapPostId&&<Button secondary onClick={()=>go(`/community/posts/${event.recapPostId}`)}>查看活动回顾</Button>}</aside></div></section>;
}

export default function CommunityEvents({api,demo,go,accountProfile,eventId,create=false}){
  const [scope,setScope]=useState('upcoming'),[creating,setCreating]=useState(create),[state,reload]=useRemote(async()=>demo?[demoEvent]:(await api.communityEvents({scope})).data,[api,demo,scope,accountProfile?.id]);
  if(eventId)return <EventDetail api={api} demo={demo} go={go} accountProfile={accountProfile} eventId={eventId}/>;
  const created=event=>{setCreating(false);reload();go(`/community/events/${event.id}`);};
  return <section className="community-events-index"><header className="community-section-heading"><div><span className="kicker">COMMUNITY EVENTS</span><h2>一起在某个时间发生</h2><p>试玩会、线上聚会、讨论和项目会议。时间均按你的本地时区显示。</p></div><Button onClick={()=>accountProfile?setCreating(value=>!value):go('/account')}>{creating?'收起创建':'＋ 组织活动'}</Button></header><nav className="community-personal-nav"><button className={scope==='upcoming'?'is-active':''} onClick={()=>setScope('upcoming')}>即将开始</button><button className={scope==='past'?'is-active':''} onClick={()=>setScope('past')}>活动回顾</button></nav>{creating&&<EventForm api={api} onCreated={created} onCancel={()=>setCreating(false)}/>}<p className="community-ranking-note">按开始时间和可参与状态排序，不使用虚假在线人数。</p>{state.status==='loading'?<div className="community-activity-list"><i className="community-activity-skeleton"/><i className="community-activity-skeleton"/></div>:state.status==='error'?<p className="community-project-state is-error">{state.error?.message||'活动暂时无法读取。'}</p>:<div className="community-activity-list">{state.data.map(event=><EventCard key={event.id} event={event} go={go}/>)}</div>}{state.status==='ready'&&!state.data.length&&<p className="community-project-state">当前没有符合条件的活动。发起一场目标明确的小型活动吧。</p>}</section>;
}
