import React,{useEffect,useState} from 'react';
import {ContributionCenterPage} from './ContributionCenter.jsx';

const statusLabels={draft:'草稿',recruiting:'招募中',active:'进行中',completed:'已完成',archived:'已归档',cancelled:'已取消'};
const demoProject={id:'demo-project',title:'像素迷阵移动端适配',summary:'让第一次在手机打开游戏的玩家也能顺利开始。',description:'一起补齐触控提示、横竖屏排版和移动端验证记录，完成后把改动关联到正式发布版本。',status:'recruiting',visibility:'public',version:1,owner:{id:'demo-author',displayName:'像素作者',handle:'pixel-author'},work:{id:'demo-work',title:'像素迷阵'},roles:[{id:'demo-role',name:'前端协作者',description:'处理触控提示和响应式样式',capacity:3,filledCount:1,requiredSkills:['HTML','CSS']}],memberCount:1,openTaskCount:1,completedTaskCount:0,isOwner:false,membership:null,myApplication:null,members:[{id:'demo-author',displayName:'像素作者',handle:'pixel-author',roleId:null}],applications:[]};

function useRemote(read,deps){
  const [state,setState]=useState({status:'loading',data:null}),[revision,setRevision]=useState(0);
  useEffect(()=>{let live=true;setState({status:'loading',data:null});Promise.resolve().then(read).then(data=>live&&setState({status:'ready',data})).catch(error=>live&&setState({status:'error',data:null,error}));return()=>{live=false;};},[...deps,revision]);
  return [state,()=>setRevision(value=>value+1)];
}
const Button=({secondary=false,children,...props})=><button type={props.onClick?'button':'submit'} className={`button button--${secondary?'secondary':'primary'}`} {...props}><span>{children}</span></button>;
const roleLines=value=>value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const [name,count='3',skills='']=line.split('|').map(part=>part.trim());return {name,capacity:Number(count),requiredSkills:skills.split(/[，,]/).map(skill=>skill.trim()).filter(Boolean)};});

function ProjectForm({api,onCreated,onCancel}){
  const [title,setTitle]=useState(''),[summary,setSummary]=useState(''),[description,setDescription]=useState(''),[roles,setRoles]=useState('协作者 | 3 | HTML, CSS'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const result=await api.communityProjectCreate({title,summary,description,roles:roleLines(roles)});onCreated(result.data);}catch(cause){setError(cause.message||'项目暂时无法创建。');}finally{setBusy(false);}};
  return <form className="community-project-form" onSubmit={submit}><div className="form-grid"><label>项目名称<input required minLength="3" maxLength="80" value={title} onChange={event=>setTitle(event.target.value)}/></label><label>一句话目标<input required minLength="10" maxLength="240" value={summary} onChange={event=>setSummary(event.target.value)}/></label></div><label>完整说明<textarea required minLength="20" maxLength="4000" value={description} onChange={event=>setDescription(event.target.value)}/></label><label>招募角色 <small>每行填写：角色名 | 人数 | 技能（逗号分隔）</small><textarea required value={roles} onChange={event=>setRoles(event.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div><Button disabled={busy}>{busy?'创建中…':'创建并开始招募'}</Button><Button secondary disabled={busy} onClick={onCancel}>取消</Button></div></form>;
}

function ProjectCard({project,go}){
  const openings=project.roles.reduce((count,role)=>count+Math.max(0,role.capacity-role.filledCount),0);
  return <article className="community-project-card"><header><div><span>{statusLabels[project.status]}</span><h3>{project.title}</h3></div><b>{openings?`还缺 ${openings} 人`:'成员已满'}</b></header><p>{project.summary}</p><div className="community-project-card__meta"><span>{project.owner.displayName} 发起</span>{project.work&&<span>关联 {project.work.title}</span>}<span>{project.completedTaskCount}/{project.completedTaskCount+project.openTaskCount||0} 个任务完成</span></div><div className="community-project-card__roles">{project.roles.slice(0,3).map(role=><span key={role.id}>{role.name} {role.filledCount}/{role.capacity}</span>)}</div><footer><span>{project.memberCount} 位成员</span><button type="button" onClick={()=>go(`/community/projects/${project.id}`)}>查看项目 →</button></footer></article>;
}

function ProjectDetail({api,demo,go,accountProfile,projectId}){
  const [state,reload]=useRemote(async()=>demo?demoProject:(await api.communityProject(projectId)).data,[api,demo,projectId,accountProfile?.id]);
  const [roleId,setRoleId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const run=async action=>{setBusy(true);setNotice('');try{if(!demo){if(action==='apply')await api.communityProjectApply(projectId,{roleId,message});else if(action==='leave')await api.communityProjectLeave(projectId);else await api.communityProjectUpdate(projectId,{expectedVersion:state.data.version,status:action});}setNotice(demo?'演示模式不保存修改。':'项目已更新。');reload();}catch(error){if(error.status===401)return go('/account');setNotice(error.message||'项目暂时无法更新。');}finally{setBusy(false);}};
  const decide=async(application,decision)=>{setBusy(true);setNotice('');try{if(!demo)await api.communityProjectDecide(projectId,application.id,{decision,expectedVersion:application.version});setNotice(demo?'演示模式不保存修改。':'申请已处理。');reload();}catch(error){setNotice(error.message||'申请暂时无法处理。');}finally{setBusy(false);}};
  if(state.status==='loading')return <p className="community-project-state">正在读取项目…</p>;
  if(state.status==='error')return <div className="community-project-state is-error"><p>{state.error?.message||'项目暂时无法读取。'}</p><button onClick={reload}>重试</button></div>;
  const project=state.data,canApply=accountProfile&&!project.isOwner&&!project.membership&&project.status==='recruiting'&&!project.myApplication?.state?.includes('pending');
  return <div className="community-project-detail"><button className="back-link" type="button" onClick={()=>go('/community/projects')}>← 返回一起做</button><header className="community-project-detail__hero"><div><span className="kicker">COMMUNITY PROJECT</span><h1>{project.title}</h1><p>{project.summary}</p><div className="community-project-detail__facts"><span>{statusLabels[project.status]}</span><span>{project.memberCount} 位成员</span><span>{project.openTaskCount} 个开放任务</span>{project.work&&<span>关联作品：{project.work.title}</span>}</div></div><aside><strong>发起人</strong><button type="button" onClick={()=>project.owner.handle&&go(`/u/${project.owner.handle}`)}>{project.owner.displayName}</button><small>项目成员关系不等于 GitHub 仓库权限。</small></aside></header>
    {notice&&<p className="contribution-message" role="status">{notice}</p>}
    <section className="community-project-detail__body"><div><h2>项目目标</h2><p>{project.description}</p><h2>招募角色</h2><div className="community-project-role-grid">{project.roles.map(role=><article key={role.id}><header><strong>{role.name}</strong><span>{role.filledCount}/{role.capacity}</span></header><p>{role.description||'项目发起人尚未补充角色说明。'}</p><div>{role.requiredSkills.map(skill=><em key={skill}>{skill}</em>)}</div></article>)}</div></div><aside><h2>成员</h2><ul>{(project.members||[]).map(member=><li key={member.id}><button type="button" onClick={()=>member.handle&&go(`/u/${member.handle}`)}>{member.displayName}</button><small>{member.id===project.owner.id?'发起人':project.roles.find(role=>role.id===member.roleId)?.name||'成员'}</small></li>)}</ul></aside></section>
    {!accountProfile&&<div className="community-project-join"><p>登录后可以申请加入项目，或直接领取允许外部贡献者参与的任务。</p><Button onClick={()=>go('/account')}>登录后参与</Button></div>}
    {project.myApplication?.state==='pending'&&<p className="community-project-join">加入申请已提交，等待发起人处理。</p>}
    {canApply&&<form className="community-project-join" onSubmit={event=>{event.preventDefault();run('apply');}}><h2>申请加入</h2><label>希望承担的角色<select required value={roleId} onChange={event=>setRoleId(event.target.value)}><option value="">请选择仍有空缺的角色</option>{project.roles.filter(role=>role.filledCount<role.capacity).map(role=><option key={role.id} value={role.id}>{role.name} · 还缺 {role.capacity-role.filledCount} 人</option>)}</select></label><label>你能提供什么<textarea required minLength="10" maxLength="1000" value={message} onChange={event=>setMessage(event.target.value)}/></label><Button disabled={busy}>提交加入申请</Button></form>}
    {(project.membership?.state==='active'||project.isOwner)&&<div className="community-project-join"><p>{project.isOwner?'你是项目发起人，可以发布进度更新。':'你已经是项目成员。'}</p><div><Button onClick={()=>go(`/community/feed/new/project/${project.id}`)}>发布项目更新</Button>{!project.isOwner&&<Button secondary disabled={busy} onClick={()=>run('leave')}>退出项目</Button>}</div></div>}
    {project.isOwner&&<section className="community-project-manage"><h2>项目管理</h2><div>{project.status==='recruiting'&&<Button disabled={busy} onClick={()=>run('active')}>进入执行阶段</Button>}{['recruiting','active'].includes(project.status)&&<Button secondary disabled={busy} onClick={()=>run('completed')}>标记完成</Button>}{!['completed','archived','cancelled'].includes(project.status)&&<Button secondary disabled={busy} onClick={()=>run('cancelled')}>取消项目</Button>}</div><h3>待处理申请</h3>{!project.applications?.some(item=>item.state==='pending')?<p>暂时没有待处理申请。</p>:project.applications.filter(item=>item.state==='pending').map(application=><article key={application.id}><strong>{application.applicant.displayName}</strong><span>{project.roles.find(role=>role.id===application.roleId)?.name}</span><p>{application.message}</p><Button disabled={busy} onClick={()=>decide(application,'approve')}>同意</Button><Button secondary disabled={busy} onClick={()=>decide(application,'reject')}>拒绝</Button></article>)}</section>}
    <section className="community-project-tasks"><div><span className="kicker">PROJECT TASKS</span><h2>项目任务</h2><p>任务继续使用原有领取、提交、验收和贡献履历，不自动授予仓库权限。</p></div><ContributionCenterPage api={api} demo={demo} go={go} accountProfile={accountProfile} embedded projectId={project.id} showHero={false}/></section>
  </div>;
}

export default function CommunityProjects({api,demo,go,accountProfile,projectId}){
  const [mine,setMine]=useState(false),[creating,setCreating]=useState(false);
  const [state,reload]=useRemote(async()=>demo?[demoProject]:(await api.communityProjects(mine?{mine:true}:{})).data,[api,demo,mine,accountProfile?.id]);
  if(projectId)return <ProjectDetail api={api} demo={demo} go={go} accountProfile={accountProfile} projectId={projectId}/>;
  const created=project=>{setCreating(false);reload();go(`/community/projects/${project.id}`);};
  return <section className="community-project-index"><header className="community-section-heading"><div><span className="kicker">BUILD TOGETHER</span><h2>值得加入的项目</h2><p>先看清目标、角色和任务，再决定加入。加入项目不会自动获得 GitHub 权限。</p></div><Button onClick={()=>accountProfile?setCreating(value=>!value):go('/account')}>{creating?'收起创建':'＋ 发起项目'}</Button></header><nav className="community-personal-nav" aria-label="项目范围"><button type="button" className={!mine?'is-active':''} onClick={()=>setMine(false)}>公开招募</button><button type="button" className={mine?'is-active':''} onClick={()=>accountProfile?setMine(true):go('/account')}>我的项目</button></nav>{creating&&<ProjectForm api={api} onCreated={created} onCancel={()=>setCreating(false)}/>} {state.status==='loading'?<p className="community-project-state">正在读取项目…</p>:state.status==='error'?<p className="community-project-state is-error">{state.error?.message||'项目暂时无法读取。'}</p>:<div className="community-project-card-grid">{state.data.map(project=><ProjectCard key={project.id} project={project} go={go}/>)}</div>}{state.status==='ready'&&!state.data.length&&<p className="community-project-state">这里还没有项目。你可以发起第一个目标明确的协作。</p>}<section className="community-independent-tasks"><div><span className="kicker">OPEN TASKS</span><h2>也可以先从一个任务开始</h2><p>不加入长期项目，也能领取作者公开的独立任务。</p></div><ContributionCenterPage api={api} demo={demo} go={go} accountProfile={accountProfile} embedded showHero={false} standalone/></section></section>;
}
