import React, { useMemo, useState } from 'react';
import { WEB_GAME_BRIDGE_PROTOCOL, WEB_GAME_BRIDGE_VERSION } from '@gamehub/web-game-sdk';
import { REALTIME_PROTOCOL, REALTIME_PROTOCOL_VERSION } from '@gamehub/multiplayer-protocol';
import webSdkPackage from '../../web-game-sdk/package.json';
import rulesSdkPackage from '../../rules-sdk/package.json';

const TEMPLATE_VERSION = '0.1.0';
const identity = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u;
const keyPattern = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u;
const modeKeyPattern = /^[a-z][a-z0-9_]{1,63}$/u;
const checklist = ['下载并运行官方模板','声明 multiplayer capability','完成双会话测试','Creator Doctor 无 error','导出规则审核包','等待平台审核签名与模式注册','使用两个真实账号发布验收'];
const sectionLinks = ['15 分钟快速开始','平台与游戏的边界','客户端 SDK / 多人桥','服务端权威规则','私密视图','本地测试','提交与签名','API / 事件 / 错误码','故障与兼容性'];
const copyText = text => globalThis.navigator?.clipboard?.writeText(text);
const downloadJson = (name,value) => { const url=URL.createObjectURL(new Blob([`${JSON.stringify(value,null,2)}\n`],{type:'application/json'})); const anchor=document.createElement('a'); anchor.href=url; anchor.download=name; anchor.click(); URL.revokeObjectURL(url); };

export default function MultiplayerDeveloperCenter({ go }) {
  const [done,setDone]=useState([]);
  const [form,setForm]=useState({workId:'',name:'双人对战',modeKey:'duel',rulesetVersion:'1.0.0',minPlayers:'2',maxPlayers:'2',turnSeconds:'60',commands:'move\npass',publicState:'棋盘、当前回合、公开计分',privateState:'当前玩家自己的手牌或秘密信息',spectatorState:'仅公开状态',publicEvents:'动作类型与公开结果，不含秘密参数'});
  const update=event=>setForm(current=>({...current,[event.target.name]:event.target.value.slice(0,400)}));
  const minPlayers=Number(form.minPlayers),maxPlayers=Number(form.maxPlayers),turnSeconds=Number(form.turnSeconds);
  const commands=[...new Set(form.commands.split(/\s+/u).map(value=>value.trim()).filter(Boolean))];
  const errors=[];
  if (!identity.test(form.workId)) errors.push('作品 ID 需为 1–128 位字母、数字或 . _ : -');
  if (!modeKeyPattern.test(form.modeKey)) errors.push('modeKey 需以小写字母开头，并且只包含小写字母、数字或下划线（2–64 位）');
  if (!keyPattern.test(form.rulesetVersion)) errors.push('rulesetVersion 格式不合法');
  if (!Number.isInteger(minPlayers)||!Number.isInteger(maxPlayers)||minPlayers<2||maxPlayers>8||minPlayers>maxPlayers) errors.push('玩家数需在 2–8 且最小值不大于最大值');
  if (!Number.isInteger(turnSeconds)||turnSeconds<10||turnSeconds>3600) errors.push('回合超时需为 10–3600 秒');
  if (!commands.length||commands.length>20||commands.some(value=>!keyPattern.test(value))) errors.push('命令类型需为 1–20 个安全标识符');
  const submission=useMemo(()=>({version:1,workId:form.workId,modeKey:form.modeKey,rulesetVersion:form.rulesetVersion,authority:'platform_authoritative',players:{min:minPlayers,max:maxPlayers},commands:commands.map(type=>({type})),views:{public:form.publicState,player:form.privateState,spectator:form.spectatorState,publicEvents:form.publicEvents},timeouts:{turnSeconds,result:'由规则适配器返回权威终局'},resignation:'使用 matches.resign，由规则适配器结算',reconnect:'以最新权威 snapshot 覆盖本地状态'}),[form,minPlayers,maxPlayers,turnSeconds,commands.join('|')]);
  const modeConfig={workId:form.workId,key:form.modeKey,name:form.name,authority:'platform_authoritative',minPlayers,maxPlayers,rulesetVersion:form.rulesetVersion,config:{turnSeconds}};
  return <main className="page multiplayer-dev-page">
    <button className="back-link" onClick={()=>go('/creator')}>← 返回创作中心</button>
    <section className="multiplayer-dev-hero"><div><span className="kicker">GAMEHUB MULTIPLAYER</span><h1>联网游戏开发者中心</h1><p>从官方双人模板开始，用真实 SDK 完成房间、权威命令、私密视图、重连与终局，再导出给平台审核。</p><div className="multiplayer-dev-actions"><a className="button button--primary" href="/downloads/gamehub-multiplayer-starter-source.zip" download>下载源码模板 v{TEMPLATE_VERSION}</a><a className="button button--secondary" href="/downloads/gamehub-multiplayer-starter-web.zip" download>下载可上传 Web ZIP</a></div></div><dl><div><dt>作者 SDK</dt><dd>{webSdkPackage.name} {webSdkPackage.version}</dd></div><div><dt>桥协议</dt><dd>{WEB_GAME_BRIDGE_PROTOCOL} / {WEB_GAME_BRIDGE_VERSION}</dd></div><div><dt>实时协议</dt><dd>{REALTIME_PROTOCOL} / {REALTIME_PROTOCOL_VERSION}</dd></div><div><dt>规则 SDK</dt><dd>{rulesSdkPackage.name} {rulesSdkPackage.version}</dd></div></dl></section>
    <nav className="multiplayer-dev-nav" aria-label="联网接入目录">{sectionLinks.map((label,index)=><a href={`#mp-${index+1}`} key={label}>{index+1}. {label}</a>)}</nav>
    <section className="multiplayer-progress"><div><span className="kicker">接入进度</span><strong>{done.length}/{checklist.length}</strong></div><ol>{checklist.map((label,index)=><li key={label}><label><input type="checkbox" checked={done.includes(index)} onChange={()=>setDone(current=>current.includes(index)?current.filter(value=>value!==index):[...current,index])}/><span>{label}</span></label></li>)}</ol></section>
    <section id="mp-1" className="multiplayer-dev-section"><span className="kicker">15 MIN QUICKSTART</span><h2>15 分钟跑通最小闭环</h2><ol><li>下载源码模板，在仓库根目录运行 <code>npm run multiplayer:doctor -- templates/multiplayer-turn-based</code>。</li><li>运行 <code>npm run multiplayer:templates</code>，得到客户端 Web ZIP 与源码提交包。</li><li>上传 Web ZIP；用两个账号完成建房、加入、准备、开始、命令、刷新恢复与认输。</li><li>将规则源码、测试和 Doctor JSON 报告交给平台审核；不要自行签名。</li></ol><p className="dev-note">模板是极小“秘密冲刺”示例，与任何具体游戏无关。客户端引用当前仓库的 <code>@gamehub/web-game-sdk</code>，打包脚本生成无 CDN 依赖的 ZIP。</p></section>
    <section id="mp-2" className="multiplayer-boundary"><article><span>平台负责</span><h2>可信基础设施</h2><p>登录、房间、席位、准备、WebSocket、commandId 幂等、revision、重连、快照、回放、超时调度与受控规则部署。</p></article><article><span>游戏负责</span><h2>规则与表现</h2><p>命令 schema、合法性、确定性状态转换、终局、玩家视图、观战视图、公开事件，以及可恢复的客户端画面。</p></article><article className="is-danger"><span>安全禁区</span><h2>永远不要这样做</h2><p>客户端保存秘密全量状态、读取 token/ticket、直连 realtime、提交 winner，或把作者服务器代码塞进 ZIP 让 API/Realtime 执行。</p></article></section>
    <section id="mp-3" className="multiplayer-dev-section"><span className="kicker">CLIENT SDK</span><h2>客户端只发送意图</h2><pre>{`const gamehub = createGameHubClient();\nawait gamehub.connect();\nconst modes = await gamehub.multiplayer.listModes();\nawait gamehub.multiplayer.connect();\nawait gamehub.multiplayer.matches.command(matchId, { type: 'move', to: 'b3' });`}</pre><p>登录凭据、realtime ticket 与 WebSocket 地址由可信父页面持有。刷新后重新订阅，并用权威 snapshot 覆盖本地预测。</p></section>
    <section id="mp-4" className="multiplayer-dev-section"><span className="kicker">INTEGRATION WIZARD</span><h2>生成提交说明与模式配置</h2><div className="multiplayer-wizard"><label>作品 ID<input name="workId" maxLength="128" value={form.workId} onChange={update} placeholder="创建作品后填写 UUID"/></label><label>模式名称<input name="name" maxLength="80" value={form.name} onChange={update}/></label><label>modeKey<input name="modeKey" maxLength="64" value={form.modeKey} onChange={update}/></label><label>rulesetVersion<input name="rulesetVersion" maxLength="64" value={form.rulesetVersion} onChange={update}/></label><label>最少玩家<input name="minPlayers" type="number" min="2" max="8" value={form.minPlayers} onChange={update}/></label><label>最多玩家<input name="maxPlayers" type="number" min="2" max="8" value={form.maxPlayers} onChange={update}/></label><label>回合超时（秒）<input name="turnSeconds" type="number" min="10" max="3600" value={form.turnSeconds} onChange={update}/></label><label>命令类型（每行一个）<textarea name="commands" maxLength="400" value={form.commands} onChange={update}/></label><label>公开状态<textarea name="publicState" maxLength="400" value={form.publicState} onChange={update}/></label><label>玩家私密状态<textarea name="privateState" maxLength="400" value={form.privateState} onChange={update}/></label><label>观战视图<textarea name="spectatorState" maxLength="400" value={form.spectatorState} onChange={update}/></label><label>公开事件<textarea name="publicEvents" maxLength="400" value={form.publicEvents} onChange={update}/></label></div>{errors.length?<ul className="form-error">{errors.map(error=><li key={error}>{error}</li>)}</ul>:<div className="wizard-output"><div><h3>creator-submission.json</h3><pre>{JSON.stringify(submission,null,2)}</pre><button onClick={()=>copyText(JSON.stringify(submission,null,2))}>复制</button><button onClick={()=>downloadJson('creator-submission.json',submission)}>导出提交说明</button></div><div><h3>平台审核后注册的模式配置</h3><pre>{JSON.stringify(modeConfig,null,2)}</pre><button onClick={()=>copyText(JSON.stringify(modeConfig,null,2))}>复制</button></div></div>}<p className="dev-note">向导只生成规范片段，不会替你生成完整游戏规则。平台审核通过并安装可信规则后，管理员才能注册此模式。</p></section>
    <section id="mp-5" className="multiplayer-dev-section"><span className="kicker">PRIVATE VIEWS</span><h2>秘密必须在服务器裁剪</h2><p><code>getPlayerView</code> 只返回该玩家可见字段，<code>getSpectatorView</code> 只返回公开字段；浏览器不能先收到全量状态再用 CSS 隐藏。公开事件也不能携带手牌、阵营或雾区内容。</p></section>
    <section id="mp-6" className="multiplayer-dev-section"><span className="kicker">LOCAL TEST</span><h2>双会话测试与机器报告</h2><p>Creator Doctor 复用生产 ZIP Validator，并检查版本边界、明显 token 引用、规则导出、identity、确定性、非当前玩家拒绝、重复计算、私密哨兵、公开事件、认输和超时终局。真实重连需用两个独立账号窗口执行；Doctor 不会伪造通过。</p><pre>{`npm run multiplayer:doctor -- ./my-game --web-zip ./my-game.zip --json --output ./artifacts/creator-doctor.json`}</pre></section>
    <section id="mp-7" className="multiplayer-dev-section"><span className="kicker">REVIEW & RELEASE</span><h2>四个不同阶段</h2><ol><li><strong>客户端 ZIP 上传：</strong>只包含浏览器资源和 platform.json。</li><li><strong>规则提交：</strong>作者导出源码、单文件 CJS bundle、测试与 Doctor 报告。</li><li><strong>平台审核签名：</strong>运营审查、受控构建、SHA-256、离线 Ed25519 签名；私钥绝不交给作者。</li><li><strong>模式注册与双账号验收：</strong>API/Realtime 同时部署只读规则包后，管理员注册模式，再做发布验收。</li></ol><button className="button button--primary" onClick={()=>go('/creator/multiplayer/submit')}>提交规则审核包</button><p className="dev-note">提交入口只把源码 ZIP 与 Doctor 证据写入隔离区，审核通过也只会进入受控构建队列，不会自动执行或上线。</p></section>
    <section id="mp-8" className="multiplayer-dev-section"><span className="kicker">REFERENCE</span><h2>API、事件与错误</h2><div className="reference-grid"><span>docs/57 · 快速开始</span><span>docs/58 · SDK / 事件 / 错误码</span><span>docs/59 · 规则适配器教程</span><span>docs/60 · 私密信息与安全禁区</span><span>docs/61 · 发布检查清单</span><span>docs/62 · 本地测试与排障</span></div></section>
    <section id="mp-9" className="multiplayer-dev-section"><span className="kicker">COMPATIBILITY</span><h2>版本兼容与变更</h2><p>当前模板 v{TEMPLATE_VERSION}；作者 SDK {webSdkPackage.version}；桥协议与实时协议均为 v1。协议 major 不匹配时拒绝连接；行为变更必须升级 rulesetVersion，旧对局继续绑定旧规则。弃用会先在文档与 Doctor warning 中出现，再经过至少一个模板版本迁移期。</p><p>现有单机作品无需添加 multiplayer capability，也不会建立多人桥。</p></section>
  </main>;
}
