const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),databaseUrl=process.env.GAMEHUB_COMMUNITY_DATABASE_URL,playwrightPath=process.env.GAMEHUB_COMMUNITY_PLAYWRIGHT_PATH;
test('contribution browser: edit, claim, retry, return, resubmit, accept and mobile layout',{skip:!databaseUrl||!playwrightPath,timeout:180000},async t=>{
 const f=await require('../contribution-fixture.cjs').createContributionFixture(databaseUrl);const {app,actors}=f;
 const task=await f.draft();let browser,ownerPage,playerPage;
 const out=path.join(root,'.runtime/contribution-acceptance');await fs.mkdir(out,{recursive:true});
 t.after(async()=>{if(ownerPage)await ownerPage.screenshot({path:path.join(out,'owner-last.png'),fullPage:true});if(playerPage)await playerPage.screenshot({path:path.join(out,'player-last.png'),fullPage:true});await browser?.close();await f.close();});
 const {build}=require('../../extensions/harness/node_modules/esbuild');
 const entry=`import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';
 import{ContributionCenterPage,CreatorContributionTasks}from${JSON.stringify(path.join(root,'packages/platform-client/src/ContributionCenter.jsx').replaceAll('\\','/'))};
 import{createApiClient}from${JSON.stringify(path.join(root,'packages/platform-api-client/src/index.mjs').replaceAll('\\','/'))};
 const actors=${JSON.stringify(actors)},actor=actors[new URL(location.href).searchParams.get('actor')||'contributor'];const api=createApiClient({getAccessToken:()=>actor.userId});
 function Fixture(){const[route,setRoute]=useState(location.hash.slice(1)||'/contribute');useEffect(()=>{const listen=()=>setRoute(location.hash.slice(1));addEventListener('hashchange',listen);return()=>removeEventListener('hashchange',listen);},[]);const go=p=>{location.hash=p;};return <div className="app" data-host="web">{route==='/creator'?<main className="page"><CreatorContributionTasks api={api} go={go}/></main>:<ContributionCenterPage api={api} go={go} accountProfile={actor.profile} taskId={route.split('/')[2]}/>}</div>;}createRoot(document.getElementById('root')).render(<React.StrictMode><Fixture/></React.StrictMode>);`;
 const bundled=await build({stdin:{contents:entry,loader:'jsx',resolveDir:root},bundle:true,write:false,format:'iife',platform:'browser',target:'chrome110',nodePaths:[path.join(root,'packages/platform-client/node_modules')],logLevel:'silent'});
 const css=await fs.readFile(path.join(root,'packages/platform-client/src/styles.css'),'utf8');
 app.get('/',async(req,reply)=>reply.type('text/html').send('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style><div id="root"></div><script src="/fixture.js"></script></html>'));
 app.get('/fixture.js',async(req,reply)=>reply.type('application/javascript').send(bundled.outputFiles[0].text));
 await app.listen({host:'127.0.0.1',port:0});const base='http://127.0.0.1:'+app.server.address().port;
 browser=await require(playwrightPath).chromium.launch({headless:true});const errors=[];
 ownerPage=await browser.newPage({viewport:{width:1365,height:1000}});playerPage=await browser.newPage({viewport:{width:1365,height:1000}});
 for(const page of [ownerPage,playerPage]){page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));}
 await ownerPage.goto(base+'/?actor=owner#/creator');
 await ownerPage.getByRole('button',{name:'编辑任务',exact:true}).click();
 await ownerPage.getByLabel('任务标题',{exact:true}).fill('修复横竖屏按钮的布局');
 await ownerPage.getByLabel('完成标准',{exact:true}).fill('修复手机横竖屏按钮重叠的问题，并验证键盘操作和桌面布局都正常。');
 await ownerPage.getByRole('button',{name:'保存修改',exact:true}).click();
 await ownerPage.getByRole('heading',{name:'修复横竖屏按钮的布局',exact:true}).waitFor();
 await ownerPage.getByRole('button',{name:'公开任务',exact:true}).click();
 await ownerPage.getByText('等待领取',{exact:true}).waitFor();
 await playerPage.goto(base+'/?actor=contributor#/contribute');
 await playerPage.getByRole('button',{name:'领取任务',exact:true}).click();
 await playerPage.getByRole('button',{name:'提交成果',exact:true}).waitFor();
 await playerPage.getByRole('button',{name:'我的任务',exact:true}).click();
 await playerPage.getByRole('button',{name:'提交成果',exact:true}).click();
 await playerPage.getByLabel('公开成果地址').fill('https://github.com/example/task-game/pull/8');
 await playerPage.getByLabel('给作者的说明').fill('已修复竖屏，桌面验证通过，请作者检查。');
 let failed=false;await playerPage.route('**/v1/contribution-tasks/*/submission',route=>{if(!failed){failed=true;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'UNAVAILABLE',message:'临时故障，请重试。'}})});}return route.continue();});
 await playerPage.getByRole('button',{name:'提交验收',exact:true}).click();
 await playerPage.getByText('临时故障，请重试。',{exact:true}).waitFor();
 assert.equal(await playerPage.getByLabel('给作者的说明').inputValue(),'已修复竖屏，桌面验证通过，请作者检查。');
 await playerPage.getByRole('button',{name:'提交验收',exact:true}).click();
 await playerPage.getByRole('button',{name:'撤回并修改',exact:true}).waitFor();
 await ownerPage.getByRole('button',{name:'刷新',exact:true}).click();
 await ownerPage.getByText('已修复竖屏，桌面验证通过，请作者检查。',{exact:true}).waitFor();
 await ownerPage.getByRole('button',{name:'退回修改',exact:true}).click();
 await ownerPage.getByLabel('修改要求',{exact:true}).fill('请补充横屏测试，确认按钮不遮挡画面。');
 await ownerPage.getByRole('button',{name:'确认退回',exact:true}).click();
 await ownerPage.getByText('已退回，修改原因已通知贡献者。',{exact:true}).waitFor();
 await playerPage.getByRole('button',{name:'刷新任务',exact:true}).click();
 await playerPage.getByText('请补充横屏测试，确认按钮不遮挡画面。',{exact:true}).waitFor();
 await playerPage.locator('.contribution-notifications summary').click();
 await playerPage.getByRole('button',{name:/需要修改.*修复横竖屏/}).click();
 await playerPage.getByRole('button',{name:'提交成果',exact:true}).click();
 assert.match(await playerPage.getByLabel('给作者的说明').inputValue(),/竖屏/);
 await playerPage.getByLabel('给作者的说明').fill('已经补齐横屏、竖屏与桌面验证，按钮无遮挡。');
 await playerPage.getByRole('button',{name:'提交验收',exact:true}).click();
 await playerPage.getByRole('button',{name:'撤回并修改',exact:true}).waitFor();
 await ownerPage.getByRole('button',{name:'刷新',exact:true}).click();
 await ownerPage.getByRole('button',{name:'验收成果',exact:true}).click();
 await ownerPage.getByRole('button',{name:'确认验收',exact:true}).click();
 await ownerPage.getByText('贡献已验收，尚未关联上线版本。',{exact:true}).waitFor();
 await ownerPage.getByRole('button',{name:'关联上线版本',exact:true}).click();
 await ownerPage.getByLabel('已发布版本',{exact:true}).selectOption(f.releaseId);
 await ownerPage.getByRole('button',{name:'保存上线版本',exact:true}).click();
 await ownerPage.getByText('已关联上线版本：v1.1',{exact:true}).waitFor();
 await playerPage.reload();await playerPage.getByText('已关联上线版本：v1.1',{exact:true}).waitFor();
 await playerPage.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 await playerPage.setViewportSize({width:360,height:900});
 assert.equal(await playerPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'narrow task detail must not overflow');
 await playerPage.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);
});
