const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),url=process.env.GAMEHUB_COMMUNITY_DATABASE_URL,playwrightPath=process.env.GAMEHUB_COMMUNITY_PLAYWRIGHT_PATH;
test('real opaque iframe: PNG/JSON downloads, authenticated share create and anonymous URL payload restore',{skip:!url||!playwrightPath,timeout:300000},async t=>{
 const {chromium}=require(playwrightPath),{build}=require('../../extensions/harness/node_modules/esbuild');const f=await require('../game-share-fixture.cjs').createGameShareFixture(url);let browser;
 const out=path.join(root,'.runtime/game-sharing-acceptance');await fs.mkdir(out,{recursive:true});
 t.after(async()=>{await browser?.close();await f.close();});
 const asImport=p=>JSON.stringify(path.join(root,p).replaceAll('\\','/'));
 const bundle=await build({stdin:{contents:"import React from 'react';import{createRoot}from'react-dom/client';import App from "+asImport('packages/platform-client/src/App.jsx')+";createRoot(document.getElementById('root')).render(<App/>);",loader:'jsx',resolveDir:root},bundle:true,write:false,platform:'browser',format:'iife',nodePaths:[path.join(root,'packages/platform-client/node_modules')],loader:{'.png':'dataurl'},define:{'import.meta.env.DEV':'false'},logLevel:'silent'});
 const game=await build({stdin:{contents:"import{createGameHubClient}from"+asImport('packages/web-game-sdk/src/index.mjs')+";const sdk=createGameHubClient();const log=value=>document.getElementById('result').textContent=JSON.stringify(value);const run=fn=>async()=>{try{log(await fn());}catch(e){log({error:e.code||e.message});}};sdk.connect().then(()=>sdk.shares.current()).then(value=>document.getElementById('current').textContent=JSON.stringify(value));document.getElementById('share').onclick=run(()=>sdk.shares.create({title:'Bingo 测试包',payload:{kind:'bingo-pack',schemaVersion:1,pack:{title:'ABC',cells:['A','B','C']}}}));document.getElementById('json').onclick=run(()=>sdk.files.download({filename:'Bingo.json',mimeType:'application/json',data:new TextEncoder().encode(JSON.stringify({kind:'bingo-pack',cells:['A','B']})).buffer}));document.getElementById('png').onclick=run(async()=>{const c=document.createElement('canvas');c.width=12;c.height=12;c.getContext('2d').fillRect(0,0,12,12);const blob=await new Promise(r=>c.toBlob(r,'image/png'));return sdk.files.download({filename:'Bingo.png',mimeType:'image/png',data:await blob.arrayBuffer()});});document.getElementById('read').onclick=run(()=>sdk.shares.current());document.getElementById('bad').onclick=run(()=>sdk.files.download({filename:'evil.html',mimeType:'text/html',data:new TextEncoder().encode('<script>bad</script>').buffer}));",resolveDir:root},bundle:true,write:false,platform:'browser',format:'iife',logLevel:'silent'});
 const css=await fs.readFile(path.join(root,'packages/platform-client/src/styles.css'),'utf8');
 f.app.get('/',async(req,reply)=>reply.type('text/html').send('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style><div id="root"></div><script src="/fixture.js"></script></html>'));
 f.app.get('/fixture.js',async(req,reply)=>reply.type('text/javascript').send(bundle.outputFiles[0].text));
 f.app.get('/index.html',async(req,reply)=>reply.type('text/html').send('<!doctype html><html><meta charset="utf-8"><button id="share">分享</button><button id="json">JSON</button><button id="png">PNG</button><button id="read">读取</button><button id="bad">恶意文件</button><pre id="current"></pre><pre id="result"></pre><script src="/game.js"></script></html>'));
 f.app.get('/game.js',async(req,reply)=>reply.type('text/javascript').send(game.outputFiles[0].text));
 await f.app.listen({host:'127.0.0.1',port:0});const port=f.app.server.address().port,base='http://127.0.0.1:'+port;f.runtimeConfig.runtimePublicPort=port;
 browser=await chromium.launch({headless:true});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1100,height:850}});const page=await context.newPage();page.setDefaultTimeout(15000);
 await page.addInitScript(actor=>{if(window!==window.parent)return;Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true});sessionStorage.setItem('gamehub.browser.credentials.v1',JSON.stringify({accessToken:actor.userId,refreshToken:'fixture-refresh',grantId:actor.grantId,profile:actor.profile}));},f.actors.owner);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/#/play/'+f.workId+'/'+f.releaseId);let frame=page.frameLocator('iframe');await frame.locator('#current').filter({hasText:'null'}).waitFor();assert.equal(await page.locator('iframe').getAttribute('sandbox'),'allow-scripts');
 for(const ext of ['json','png']){await frame.locator('#'+ext).click();await page.getByRole('dialog',{name:'保存游戏文件'}).waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:'选择位置并保存'}).click();const d=await download;assert.equal(d.suggestedFilename(),'Bingo.'+ext);await d.saveAs(path.join(out,'Bingo.'+ext));await frame.locator('#result').filter({hasText:'download_started'}).waitFor();}
 assert.equal(JSON.parse(await fs.readFile(path.join(out,'Bingo.json'),'utf8')).kind,'bingo-pack');assert.deepEqual([...(await fs.readFile(path.join(out,'Bingo.png'))).subarray(0,8)],[137,80,78,71,13,10,26,10]);
 await frame.locator('#bad').click();await frame.locator('#result').filter({hasText:'FILE_EXPORT_INVALID'}).waitFor();assert.equal(await page.locator('dialog').count(),0);
 await frame.locator('#json').click();await page.getByRole('button',{name:'取消',exact:true}).click();await frame.locator('#result').filter({hasText:'FILE_EXPORT_CANCELLED'}).waitFor();
 await frame.locator('#share').click();await frame.locator('#result').filter({hasText:'expiresAt'}).waitFor();const share=JSON.parse(await frame.locator('#result').textContent());assert.match(share.code,/^[A-Za-z0-9_-]{32}$/);assert.equal(share.url,'https://mooyu.fun/#/s/'+share.code);
 const anonymous=await browser.newContext();const other=await anonymous.newPage();await other.goto(base+'/#/s/'+share.code);const shared=other.frameLocator('iframe');await shared.locator('#current').filter({hasText:'bingo-pack'}).waitFor();const restored=JSON.parse(await shared.locator('#current').textContent());assert.equal(restored.releaseId,f.releaseId);assert.deepEqual(restored.payload.pack.cells,['A','B','C']);
 await shared.locator('#share').click();await shared.locator('#result').filter({hasText:'AUTH_REQUIRED'}).waitFor();await shared.locator('#read').click();await shared.locator('#result').filter({hasText:'bingo-pack'}).waitFor();
 await other.screenshot({path:path.join(out,'share-restored.png'),fullPage:true});
 await f.pool.query("UPDATE works SET state='withdrawn' WHERE id=$1",[f.workId]);await shared.locator('#read').click();await shared.locator('#result').filter({hasText:'SHARE_UNAVAILABLE'}).waitFor();await other.reload();await other.getByRole('heading',{name:'分享不可用'}).waitFor();assert.equal(await other.locator('iframe').count(),0);
 assert.deepEqual(errors,[]);await anonymous.close();await context.close();
});
