const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs/promises'), path = require('node:path');
const root = path.resolve(__dirname,'../..'), url = process.env.GAMEHUB_COMMUNITY_DATABASE_URL, playwrightPath = process.env.GAMEHUB_COMMUNITY_PLAYWRIGHT_PATH;
test('work editor browser: prefill, immutable kind, validation, real conflict, retry and public update without publishing', { skip: !url || !playwrightPath, timeout: 300000 }, async t => {
  const f = await require('../work-edit-fixture.cjs').createWorkEditFixture(url), { app, workId, pool } = f;
  if (t.signal.aborted) { await f.close(); return; }
  const out = path.join(root,'.runtime/work-edit-acceptance'); await fs.mkdir(out,{recursive:true});
  let browser, page; t.after(async()=>{if(page)await page.screenshot({path:path.join(out,'last.png'),fullPage:true});await browser?.close();await f.close();});
  const before = await f.protectedState(), requests = [];
  app.addHook('onRequest',async req=>requests.push({method:req.method,url:req.url,headers:req.headers}));
  app.post('/v1/analytics/events',async()=>({data:{accepted:1}}));
  app.get('/v1/creator/feedback',async()=>({data:[]})); app.get('/v1/creator/contribution-tasks',async()=>({data:[]})); app.get('/v1/contribution-notifications',async()=>({data:{items:[],unreadCount:0}}));
  const {build}=require('../../extensions/harness/node_modules/esbuild');
  const bundle=await build({stdin:{contents:["import React from 'react';import{createRoot}from'react-dom/client';",'import App from '+JSON.stringify(path.join(root,'packages/platform-client/src/App.jsx').replaceAll('\\','/'))+';','import{createApiClient}from'+JSON.stringify(path.join(root,'packages/platform-api-client/src/index.mjs').replaceAll('\\','/'))+';',`const api=createApiClient({getAccessToken:()=>${JSON.stringify(f.actors.owner.userId)}});createRoot(document.getElementById('root')).render(<React.StrictMode><App apiClient={api} demo={false}/></React.StrictMode>);`].join('\n'),loader:'jsx',resolveDir:root},bundle:true,write:false,format:'iife',platform:'browser',nodePaths:[path.join(root,'packages/platform-client/node_modules')],loader:{'.png':'dataurl'},define:{'import.meta.env.DEV':'false'},logLevel:'silent'});
  const css=await fs.readFile(path.join(root,'packages/platform-client/src/styles.css'),'utf8');
  app.get('/',async(req,reply)=>reply.type('text/html').send('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style><div id="root"></div><script src="/fixture.js"></script></html>'));
  app.get('/fixture.js',async(req,reply)=>reply.type('text/javascript').send(bundle.outputFiles[0].text));
  await app.listen({host:'127.0.0.1',port:0});const base='http://127.0.0.1:'+app.server.address().port;
  browser=await require(playwrightPath).chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1365,height:1000}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base+'/#/creator');
  await page.locator('.creator-entry').filter({has:page.getByRole('heading',{name:'纸飞机',exact:true})}).getByRole('button',{name:'编辑资料',exact:true}).click();
  await page.getByText('保存后，公开详情立即更新。',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('作品名称',{exact:true}).inputValue(),'纸飞机');assert.equal(await page.getByLabel('预计时长（分钟）').inputValue(),'7');assert.equal(await page.getByLabel('使用的 Coding Agent').inputValue(),'我的 Agent');
  assert.equal(await page.getByLabel('作品类型',{exact:true}).getAttribute('readonly'),'');
  await page.getByLabel('作品名称',{exact:true}).fill('我的新标题');
  await page.getByLabel('开源许可证',{exact:true}).fill('');await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('开源地址和许可证需要同时填写。',{exact:true}).waitFor();
  assert.equal(requests.filter(req=>req.method==='PATCH').length,0);
  await page.getByLabel('GitHub 仓库',{exact:true}).fill('');
  await pool.query("UPDATE works SET title='另一个窗口的标题',revision=revision+1 WHERE id=$1",[workId]);
  await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByRole('button',{name:'重新载入最新资料',exact:true}).waitFor();
  assert.equal(await page.getByLabel('作品名称',{exact:true}).inputValue(),'我的新标题');assert.equal(await page.getByRole('button',{name:'保存资料',exact:true}).isDisabled(),true);
  await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'conflict.png'),fullPage:true});
  await page.getByRole('button',{name:'重新载入最新资料',exact:true}).click();await page.waitForFunction(()=>document.querySelector('input[name=title]')?.value==='另一个窗口的标题');
  await page.getByLabel('作品名称',{exact:true}).fill('改好的纸飞机');await page.getByLabel('一句话介绍',{exact:true}).fill('更新后的介绍，立即展示在公开详情。');await page.getByLabel('玩法说明',{exact:true}).fill('使用鼠标或键盘控制飞机。');await page.getByLabel('预计时长（分钟）').fill('12');await page.getByLabel('发现标签',{exact:true}).fill('竞速，休闲，竞速');await page.getByLabel('使用的 Coding Agent').fill('Cursor');await page.getByLabel('GitHub 仓库',{exact:true}).fill('');await page.getByLabel('开源许可证',{exact:true}).fill('');
  await page.setViewportSize({width:360,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
  let dropReply=true;await page.route('**/v1/creator/works/'+workId,async route=>{if(route.request().method()==='PATCH'&&dropReply){dropReply=false;const response=await route.fetch();assert.equal(response.status(),200);return route.abort('failed');}return route.continue();});
  await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('暂时无法连接 GameHub，请稍后重试。',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('作品名称',{exact:true}).inputValue(),'改好的纸飞机');
  await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('《改好的纸飞机》资料已保存。',{exact:true}).waitFor();
  const row=page.locator('.creator-entry').filter({has:page.getByRole('heading',{name:'改好的纸飞机',exact:true})});await row.getByText('Web · 资料版本 2',{exact:true}).waitFor();
  const patches=requests.filter(req=>req.method==='PATCH');assert.equal(patches.length,3);assert.equal(patches[1].headers['idempotency-key'],patches[2].headers['idempotency-key']);assert.equal(patches[1].headers['if-match'],`"work-${workId}-1"`);
  const publicly=(await app.inject({url:'/v1/works/'+workId})).json().data;assert.equal(publicly.title,'改好的纸飞机');assert.equal(publicly.repositoryUrl,null);assert.equal(publicly.licenseSpdx,null);assert.equal(publicly.kind,'game');assert.equal(publicly.estimatedMinutes,12);assert.deepEqual(publicly.tags,['竞速','休闲']);assert.equal(publicly.targets[0].currentReleaseId,f.releaseId);
  await page.goto(base+'/#/creator/works/'+f.draftId+'/edit');await page.getByRole('heading',{name:'编辑作品资料',exact:true}).waitFor();await page.getByText('只修改资料；保存不会发布作品或替换游戏包。',{exact:true}).waitFor();await page.getByRole('button',{name:'取消',exact:true}).click();
  assert.deepEqual(await f.protectedState(),before);assert.deepEqual(requests.filter(req=>!['GET','PATCH'].includes(req.method)&&!req.url.startsWith('/v1/analytics/')),[]);assert.deepEqual(errors,[]);
});
