const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const image=process.env.GAMEHUB_COMMUNITY_IMAGE_TEST_IMAGE;
test('community codec runs in a networkless, read-only 256 MiB container',{skip:!image,timeout:60000},async t=>{
  const {CommunityMediaStore}=await import('../../apps/api/src/community-media-store.mjs');
  const {createCommunityImageRunner}=await import('../../apps/api/src/community-image-runner.mjs');
  const sharp=require('../../apps/api/node_modules/sharp');
  const directory=await fs.mkdtemp(path.join(os.tmpdir(),'gamehub-codec-test-'));
  const name='gamehub-codec-test-'+crypto.randomUUID();
  const mediaRoot=path.join(directory,'media'),processorRoot=path.join(directory,'processor');
  await fs.mkdir(mediaRoot);await fs.mkdir(processorRoot);
  const docker=args=>execFileSync('docker',args,{windowsHide:true,timeout:30000,encoding:'utf8'});
  let started=false;
  t.after(async()=>{if(started)docker(['stop','--time','10',name]);await fs.rm(directory,{recursive:true,force:true});});
  docker(['run','-d','--rm','--name',name,'--network','none','--read-only','--memory','256m','--cpus','0.5','--pids-limit','32','--cap-drop','ALL','--security-opt','no-new-privileges','--tmpfs','/tmp:rw,noexec,nosuid,size=32m','--mount','type=bind,source='+mediaRoot+',target=/data/community-media,readonly','--mount','type=bind,source='+processorRoot+',target=/data/community-processor',image,'node','apps/api/src/community-image-service.mjs']);started=true;
  const config=JSON.parse(docker(['inspect',name]))[0];
  assert.equal(config.HostConfig.NetworkMode,'none');assert.equal(config.HostConfig.ReadonlyRootfs,true);assert.equal(config.HostConfig.Memory,268435456);
  assert.equal(config.Config.User,'node');assert.equal(config.Config.Env.some(v=>v.startsWith('DATABASE_URL=')),false);
  const store=new CommunityMediaStore(mediaRoot),runner=createCommunityImageRunner({root:processorRoot,mediaRoot,mode:'isolated'}),id=crypto.randomUUID(),lease=crypto.randomUUID();
  const input=await sharp({create:{width:2200,height:1200,channels:3,background:'#7561ad'}}).png().toBuffer();
  await store.put(id,'input',input);
  const result=await runner.run({id},lease);
  assert.equal(result.report.format,'png');assert.equal(result.report.variants.display.width,1600);
  assert.ok((await fs.stat(path.join(result.output,'thumb.webp'))).size<163840);
  await runner.cleanup(lease);
  const invalid=crypto.randomUUID();
  await store.put(invalid,'input',Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"></svg>'));
  const rejectedLease=crypto.randomUUID();
  await assert.rejects(runner.run({id:invalid},rejectedLease),{code:'IMAGE_INVALID'});
  await runner.cleanup(rejectedLease);
  const partial=path.join(processorRoot,'requests',crypto.randomUUID()+'.json.'+crypto.randomUUID()+'.partial');
  await fs.writeFile(partial,'{}');const old=new Date(Date.now()-180000);await fs.utimes(partial,old,old);
  await runner.prune();
  await assert.rejects(fs.stat(partial),{code:'ENOENT'});
});
