const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const databaseUrl=process.env.GAMEHUB_COMMUNITY_DATABASE_URL;
test('contribution PostgreSQL: two-account workflow, private history, stale review and work withdrawal',{skip:!databaseUrl,timeout:180000},async t=>{
 const f=await require('../contribution-fixture.cjs').createContributionFixture(databaseUrl);t.after(()=>f.close());
 const {pool,service,actors,app,workId,releaseId}=f,{owner,contributor,stranger}=actors;
 const request=async(actor,method,url,payload,status=200)=>{const r=await app.inject({method,url,...(actor?{headers:{authorization:'Bearer '+actor.userId}}:{}),...(payload?{payload}:{})});assert.equal(r.statusCode,status,r.body);return r.json().data;};
 const action=async(task,kind,extra={})=>request(owner,'PATCH','/v1/creator/contribution-tasks/'+task.id,{action:kind,expectedVersion:task.version,...extra});
 let task=await f.draft();
 await request(null,'GET','/v1/contribution-tasks/'+task.id,null,404);
 await request(stranger,'PATCH','/v1/creator/contribution-tasks/'+task.id,{action:'publish',expectedVersion:task.version},403);
 task=await action(task,'edit',{title:'修复手机按钮的重叠',description:'在窄屏设备上修复触屏按钮重叠，同时验证桌面和横屏仍能正常使用。',difficulty:'intermediate',skills:['CSS','测试']});
 assert.equal(task.title,'修复手机按钮的重叠');
 task=await action(task,'close',{reason:'暂时暂停招募，补充验收标准。'});
 task=await action(task,'edit',{title:'修复手机按钮的重叠',description:task.description,difficulty:'starter',skills:['CSS']});
 task=await action(task,'reopen');
 const race=await Promise.allSettled([service.claim(contributor,task.id),service.claim(stranger,task.id)]);
 assert.equal(race.filter(r=>r.status==='fulfilled').length,1,'exactly one claimant');
 task=(await service.get(owner,task.id));const claimant=Object.values(actors).find(a=>a.userId===task.claimant.id),other=claimant===contributor?stranger:contributor;
 assert.ok(task.claimExpiresAt);await request(claimant,'POST',`/v1/contribution-tasks/${task.id}/renew`);
 await request(other,'POST',`/v1/contribution-tasks/${task.id}/submission`,{url:'https://example.com/result',note:'无权提交的测试说明'},403);
 task=await request(claimant,'POST',`/v1/contribution-tasks/${task.id}/submission`,{url:'https://github.com/example/task-game/pull/7',note:'已修复重叠，360 像素与桌面都通过验证。'});
 const stale=task;
 assert.equal((await service.get(owner,task.id)).submissionNote,'已修复重叠，360 像素与桌面都通过验证。');
 assert.equal((await service.get(other,task.id)).submissionNote,'');
 assert.equal((await service.get(null,task.id)).events.length,0);
 await request(owner,'PATCH',`/v1/creator/contribution-tasks/${task.id}`,{action:'request_changes',expectedVersion:task.version,reason:''},400);
 task=await action(task,'request_changes',{reason:'请补充横屏测试，并修复长标题截断。'});
 const ownNotices=await request(claimant,'GET','/v1/contribution-notifications');
 const returned=ownNotices.items.find(n=>n.action==='changes_requested');assert.match(returned.details.reason,/横屏/);assert.equal(returned.read,false);
 assert.equal((await request(other,'POST',`/v1/contribution-notifications/${returned.id}/read`)).updated,0);
 assert.equal((await request(claimant,'POST',`/v1/contribution-notifications/${returned.id}/read`)).updated,1);
 task=await service.submit(claimant,task.id,{url:'https://github.com/example/task-game/pull/7',note:'已补充横屏测试，长标题也完整显示。',expectedVersion:task.version});
 await request(owner,'PATCH',`/v1/creator/contribution-tasks/${task.id}`,{action:'complete',expectedVersion:stale.version},409);
 task=await request(claimant,'POST',`/v1/contribution-tasks/${task.id}/withdraw`);assert.equal(task.status,'claimed');assert.match(task.submissionNote,/横屏/);
 task=await service.submit(claimant,task.id,{url:'https://github.com/example/task-game/pull/7',note:'最终提交：窄屏、横屏、桌面全部通过。',expectedVersion:task.version});
 await request(owner,'PATCH',`/v1/creator/contribution-tasks/${task.id}`,{action:'complete',expectedVersion:task.version,releaseId:crypto.randomUUID()},409);
 task=await action(task,'complete');assert.equal(task.resolvedRelease,null);
 assert.equal((await pool.query('SELECT status FROM creator_feedback WHERE id=$1',[task.feedbackId])).rows[0].status,'resolved');
 const feedbacks=await f.feedback.list(owner);assert.equal(feedbacks.find(i=>i.id===task.feedbackId).contributionTaskId,task.id);
 task=await action(task,'link_release',{releaseId});assert.equal(task.resolvedRelease.label,'v1.1');
 const profile=await request(null,'GET','/v1/profiles/'+claimant.profile.handle);assert.ok(profile.contributions.some(c=>c.taskId===task.id));
 await request(claimant,'POST',`/v1/contribution-tasks/${task.id}/release`,null,409);
 let second=await f.draft();second=await action(second,'publish');await service.claim(claimant,second.id);second=await service.submit(claimant,second.id,{url:'https://example.com/private-result',note:'只给作者的历史说明'});
 await service.release(claimant,second.id);await service.claim(other,second.id);await service.submit(other,second.id,{url:'https://example.com/other',note:'另一位贡献者的私密说明'});
 const former=await service.get(claimant,second.id);assert.equal(former.submissionNote,'');assert.equal(former.events.some(e=>e.details.submissionNote==='另一位贡献者的私密说明'),false);assert.ok(former.events.some(e=>e.details.submissionNote==='只给作者的历史说明'));
 await pool.query("UPDATE works SET state='withdrawn',visibility='private' WHERE id=$1",[workId]);
 const hidden=await service.get(other,second.id);assert.equal(hidden.status,'closed');assert.equal(hidden.claimant,null);assert.ok(hidden.events.some(e=>e.action==='work_unavailable'));
 assert.ok((await service.listPublic(other,{mine:true})).some(i=>i.id===second.id));
 assert.equal((await service.listPublic(null)).length,0);
 await assert.rejects(()=>service.claim(other,second.id),e=>e.code==='WORK_NOT_PUBLIC');
 await assert.rejects(()=>service.creatorAction(owner,second.id,{action:'reopen',expectedVersion:hidden.version}),e=>e.code==='WORK_NOT_PUBLIC');
 await pool.query("UPDATE works SET state='published',visibility='public' WHERE id=$1",[workId]);
 const reopened=await action(hidden,'reopen');assert.equal(reopened.claimant,null);assert.equal(reopened.status,'open');
});

test('contribution PostgreSQL: pagination, claim expiry, quotas and immutable audit',{skip:!databaseUrl,timeout:180000},async t=>{
 const f=await require('../contribution-fixture.cjs').createContributionFixture(databaseUrl);t.after(()=>f.close());
 const {pool,service,actors,workId}=f,{owner,contributor,stranger}=actors;
 async function seed(){const id=crypto.randomUUID();await pool.query("INSERT INTO contribution_tasks(id,work_id,author_user_id,title,description,difficulty,status,published_at,repository_url) VALUES($1,$2,$3,'分页和名额测试任务','确认分页和名额不受任务总量影响，并验证正常协作流程可用。','starter','open',now(),'https://github.com/example/task-game')",[id,workId,owner.userId]);return id;}
 const id=await seed();await service.claim(contributor,id);
 for(let i=0;i<61;i++)await seed();
 assert.equal((await service.listPublic(contributor)).some(t=>t.id===id),false);
 assert.ok((await service.listPublic(contributor,{mine:true})).some(t=>t.id===id));
 const first=await service.listPublic(null,{limit:20}),next=await service.listPublic(null,{limit:20,offset:20});assert.equal(first.length,20);assert.equal(next.length,20);assert.equal(new Set([...first,...next].map(t=>t.id)).size,40);
 assert.equal((await service.listForCreator(owner,{limit:20,offset:60})).length,2);
 await pool.query("UPDATE contribution_tasks SET claim_expires_at=now()-interval '1 second' WHERE id=$1",[id]);
 const expired=await service.get(contributor,id);assert.equal(expired.status,'open');assert.equal(expired.claimant,null);assert.ok(expired.events.some(e=>e.action==='claim_expired'));
 assert.ok((await service.notifications(contributor)).items.some(e=>e.action==='claim_expired'&&!e.read));
 await assert.rejects(()=>service.renew(contributor,id),e=>e.code==='CONTRIBUTION_TASK_NOT_CLAIMED');
 await service.claim(stranger,id);assert.equal((await service.get(contributor,id)).claimant,null);
 const ids=await Promise.all([seed(),seed(),seed(),seed()]);
 const claims=await Promise.allSettled(ids.map(t=>service.claim(contributor,t)));assert.equal(claims.filter(r=>r.status==='fulfilled').length,3);assert.equal(claims.find(r=>r.status==='rejected').reason.code,'CONTRIBUTION_CLAIM_LIMIT');
 await assert.rejects(()=>pool.query("UPDATE contribution_task_events SET details='{}'"),/append-only/);
 await assert.rejects(()=>pool.query('DELETE FROM contribution_task_events'),/append-only/);
 assert.throws(()=>service.listPublic(null,{mine:true}),e=>e.code==='UNAUTHORIZED');
});

test('contribution migration upgrades existing claims and closes already hidden tasks without losing submissions',{skip:!databaseUrl,timeout:180000},async t=>{
 const path=require('node:path');const {createCommunityTestDatabase}=require('../community-database.cjs');
 const {loadMigrations,applyMigrations}=await import('../../apps/api/src/migrations.mjs');
 const db=await createCommunityTestDatabase(databaseUrl);t.after(()=>db.close());const pool=db.pool;
 const directory=path.resolve(__dirname,'../../apps/api/migrations'),migrations=await loadMigrations(directory),client=await pool.connect();
 try{for(const migration of migrations.slice(0,53)){await client.query('BEGIN');try{await client.query(migration.body);await client.query('INSERT INTO schema_migrations(version,checksum_sha256) VALUES($1,$2)',[migration.version,migration.checksum]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}}}finally{client.release();}
 const owner=crypto.randomUUID(),player=crypto.randomUUID(),hiddenWork=crypto.randomUUID(),publicWork=crypto.randomUUID(),hiddenTask=crypto.randomUUID(),liveTask=crypto.randomUUID();
 for(const id of [owner,player])await pool.query("INSERT INTO users(id,display_name) VALUES($1,'旧版本玩家')",[id]);
 await pool.query("INSERT INTO works(id,owner_user_id,title,kind,state,visibility) VALUES($1,$2,'已撤下作品','game','withdrawn','private'),($3,$2,'公开作品','game','published','public')",[hiddenWork,owner,publicWork]);
 await pool.query("INSERT INTO contribution_tasks(id,work_id,author_user_id,claimant_user_id,title,description,difficulty,status,published_at,claimed_at,submitted_at,submission_url,submission_note) VALUES($1,$2,$3,$4,'历史待验收任务','确认旧版本迁移后仍然保留提交记录，并且正确释放领取名额。','starter','submitted',now(),now(),now(),'https://example.com/old-result','历史私有提交说明')",[hiddenTask,hiddenWork,owner,player]);
 await pool.query("INSERT INTO contribution_tasks(id,work_id,author_user_id,claimant_user_id,title,description,difficulty,status,published_at,claimed_at) VALUES($1,$2,$3,$4,'历史进行中任务','确认迁移后正常的公开任务仍保持领取，并给予新的领取期限。','starter','claimed',now(),now()-interval '30 days')",[liveTask,publicWork,owner,player]);
 const result=await applyMigrations(pool,directory);assert.deepEqual(result.applied,['0054_contribution_workflow.sql']);assert.equal(result.total,54);
 const hidden=(await pool.query('SELECT * FROM contribution_tasks WHERE id=$1',[hiddenTask])).rows[0];assert.equal(hidden.status,'closed');assert.equal(hidden.claimant_user_id,null);
 const event=(await pool.query("SELECT * FROM contribution_task_events WHERE task_id=$1 AND action='work_unavailable'",[hiddenTask])).rows[0];assert.equal(event.details.submissionNote,'历史私有提交说明');
 assert.equal((await pool.query('SELECT * FROM contribution_notifications WHERE event_id=$1 AND user_id=$2',[event.id,player])).rowCount,1);
 assert.equal((await pool.query('SELECT * FROM contribution_task_participants WHERE task_id=$1 AND user_id=$2',[hiddenTask,player])).rowCount,1);
 const live=(await pool.query('SELECT * FROM contribution_tasks WHERE id=$1',[liveTask])).rows[0];assert.equal(live.status,'claimed');assert.ok(new Date(live.claim_expires_at).getTime()>Date.now()+6*86400000);
 assert.equal((await applyMigrations(pool,directory)).applied.length,0,'upgrade is idempotent through migration journal');
});
