import { CommunityError } from './community-errors.mjs';
const params = name => ({type:'object',required:[name],additionalProperties:false,properties:{[name]:{type:'string',format:'uuid'}}});
const body = {type:'object',additionalProperties:false,required:['channel','title','blocks'],properties:{channel:{type:'string',enum:['game','ai','computing']},title:{type:'string',minLength:1,maxLength:120},blocks:{type:'array',minItems:1,maxItems:32,items:{type:'object'}},projectId:{type:['string','null'],format:'uuid'}}};
export function registerCommunityRoutes(app,{service,media,requireAuth}) {
  app.addHook('onRequest',async(request,reply)=>{
    const pathname=request.url.split('?')[0];
    if(!pathname.startsWith('/v1/community/')&&!pathname.startsWith('/v1/admin/community/'))return;
    reply.header('Cache-Control','no-store');
    if(pathname!=='/v1/community/capabilities'&&!service.config.enabled)throw new CommunityError('COMMUNITY_DISABLED',503,'分享板块暂未开放。');
    if(pathname.includes('/media')&&request.method!=='GET'&&!service.config.imagesEnabled)throw new CommunityError('COMMUNITY_IMAGES_DISABLED',503,'图片上传暂未开放。');
  });
  const optionalAuth=async request=>{if(request.headers.authorization)await requireAuth(request);};
  const send=(reply,data)=>{if(data?.version)reply.header('ETag','"'+data.version+'"');return {data};};
  app.get('/v1/community/capabilities',{preHandler:optionalAuth},async request=>({data:await service.capabilities(request.actor)}));
  app.get('/v1/community/posts',{preHandler:optionalAuth,schema:{querystring:{type:'object',additionalProperties:false,properties:{channel:{type:'string',enum:['game','ai','computing']},author:{type:'string',format:'uuid'},cursor:{type:'string',maxLength:800}}}}},async request=>({data:await service.list(request.actor,request.query)}));
  for(const kind of ['posts','bookmarks'])app.get('/v1/community/me/'+kind,{preHandler:requireAuth,schema:{querystring:{type:'object',additionalProperties:false,properties:{cursor:{type:'string',maxLength:800}}}}},async request=>({data:await service.list(request.actor,{...request.query,kind:kind==='posts'?'mine':'bookmarks'})}));
  app.get('/v1/community/me/posts/:postId',{preHandler:requireAuth,schema:{params:params('postId')}},async(request,reply)=>send(reply,await service.get(request.actor,request.params.postId,{manage:true})));
  app.get('/v1/community/posts/:postId',{preHandler:optionalAuth,schema:{params:params('postId')}},async(request,reply)=>send(reply,await service.get(request.actor,request.params.postId)));
  app.post('/v1/community/posts',{preHandler:requireAuth,bodyLimit:32768,schema:{body}},async(request,reply)=>send(reply,await service.save(request.actor,null,request.body,null,request.headers['idempotency-key'])));
  app.patch('/v1/community/posts/:postId',{preHandler:requireAuth,bodyLimit:32768,schema:{params:params('postId'),body}},async(request,reply)=>send(reply,await service.save(request.actor,request.params.postId,request.body,request.headers['if-match'],request.headers['idempotency-key'])));
  app.post('/v1/community/posts/:postId/submit',{preHandler:requireAuth,schema:{params:params('postId')}},async(request,reply)=>send(reply,await service.submit(request.actor,request.params.postId,request.headers['if-match'],request.headers['idempotency-key'])));
  app.post('/v1/community/posts/:postId/withdraw',{preHandler:requireAuth,schema:{params:params('postId')}},async(request,reply)=>send(reply,await service.withdraw(request.actor,request.params.postId,request.headers['if-match'])));
  app.delete('/v1/community/posts/:postId',{preHandler:requireAuth,schema:{params:params('postId')}},async request=>({data:await service.withdraw(request.actor,request.params.postId,request.headers['if-match'],true)}));
  for(const type of ['like','bookmark'])for(const method of ['PUT','DELETE'])app.route({method,url:'/v1/community/posts/:postId/'+type,preHandler:requireAuth,schema:{params:params('postId')},handler:async request=>({data:await service.interaction(request.actor,request.params.postId,type,method==='PUT')})});
  app.post('/v1/community/posts/:postId/reports',{preHandler:requireAuth,schema:{params:params('postId'),body:{type:'object',additionalProperties:false,required:['category','details'],properties:{category:{type:'string',enum:['unsafe','harassment','copyright','spam','other']},details:{type:'string',minLength:1,maxLength:1000}}}}},async request=>({data:await service.report(request.actor,request.params.postId,request.body)}));
  app.get('/v1/admin/community/review',{preHandler:requireAuth,schema:{querystring:{type:'object',additionalProperties:false,properties:{cursor:{type:'string',maxLength:800}}}}},async request=>({data:await service.reviewQueue(request.actor,request.query)}));
  app.post('/v1/admin/community/posts/:postId/decisions',{preHandler:requireAuth,schema:{params:params('postId'),body:{type:'object',additionalProperties:false,required:['action','revisionId','reason'],properties:{action:{type:'string',enum:['approve','reject','hide','restore','dismiss_reports']},revisionId:{type:'string',format:'uuid'},reason:{type:'string',minLength:1,maxLength:1000}}}}},async(request,reply)=>send(reply,await service.decide(request.actor,request.params.postId,request.body,request.headers['if-match'],request.headers['idempotency-key'])));
  app.put('/v1/admin/community/members/:userId',{preHandler:requireAuth,schema:{params:params('userId'),body:{type:'object',additionalProperties:false,required:['allowed','reason'],properties:{allowed:{type:'boolean'},reason:{type:'string',minLength:1,maxLength:1000}}}}},async request=>({data:await service.allowMember(request.actor,request.params.userId,request.body)}));
  if(service.projects){
    const projectParams=params('projectId');
    const role={type:'object',additionalProperties:false,required:['name','capacity'],properties:{name:{type:'string',minLength:2,maxLength:40},description:{type:'string',maxLength:500},capacity:{type:'integer',minimum:1,maximum:20},requiredSkills:{type:'array',maxItems:8,uniqueItems:true,items:{type:'string',minLength:1,maxLength:30}}}};
    const projectFields={title:{type:'string',minLength:3,maxLength:80},summary:{type:'string',minLength:10,maxLength:240},description:{type:'string',minLength:20,maxLength:4000},workId:{type:['string','null'],format:'uuid'}};
    app.get('/v1/community/projects',{preHandler:optionalAuth,schema:{querystring:{type:'object',additionalProperties:false,properties:{status:{type:'string',enum:['all','draft','recruiting','active','completed','archived','cancelled']},mine:{type:'boolean'},limit:{type:'integer',minimum:1,maximum:50},offset:{type:'integer',minimum:0}}}}},async request=>({data:await service.projects.list(request.actor,request.query)}));
    app.post('/v1/community/projects',{preHandler:requireAuth,schema:{body:{type:'object',additionalProperties:false,required:['title','summary','description','roles'],properties:{...projectFields,roles:{type:'array',minItems:1,maxItems:8,items:role}}}}},async(request,reply)=>send(reply,await service.projects.create(request.actor,request.body)));
    app.get('/v1/community/projects/:projectId',{preHandler:optionalAuth,schema:{params:projectParams}},async(request,reply)=>send(reply,await service.projects.get(request.actor,request.params.projectId)));
    app.patch('/v1/community/projects/:projectId',{preHandler:requireAuth,schema:{params:projectParams,body:{type:'object',additionalProperties:false,required:['expectedVersion'],properties:{...projectFields,expectedVersion:{type:'integer',minimum:1},status:{type:'string',enum:['draft','recruiting','active','completed','archived','cancelled']},visibility:{type:'string',enum:['public','unlisted']}}}}},async(request,reply)=>send(reply,await service.projects.update(request.actor,request.params.projectId,request.body)));
    app.post('/v1/community/projects/:projectId/applications',{preHandler:requireAuth,schema:{params:projectParams,body:{type:'object',additionalProperties:false,required:['roleId','message'],properties:{roleId:{type:'string',format:'uuid'},message:{type:'string',minLength:10,maxLength:1000}}}}},async request=>({data:await service.projects.apply(request.actor,request.params.projectId,request.body)}));
    app.post('/v1/community/projects/:projectId/applications/:applicationId/decision',{preHandler:requireAuth,schema:{params:{type:'object',additionalProperties:false,required:['projectId','applicationId'],properties:{projectId:{type:'string',format:'uuid'},applicationId:{type:'string',format:'uuid'}}},body:{type:'object',additionalProperties:false,required:['decision','expectedVersion'],properties:{decision:{type:'string',enum:['approve','reject']},expectedVersion:{type:'integer',minimum:1}}}}},async request=>({data:await service.projects.decide(request.actor,request.params.projectId,request.params.applicationId,request.body)}));
    app.post('/v1/community/projects/:projectId/leave',{preHandler:requireAuth,schema:{params:projectParams}},async request=>({data:await service.projects.leave(request.actor,request.params.projectId)}));
  }
  if(service.events&&service.parties&&service.experience){
    const eventParams=params('eventId'),partyParams=params('partyId');
    const eventProperties={
      title:{type:'string',minLength:3,maxLength:100},summary:{type:'string',minLength:10,maxLength:500},eventType:{type:'string',enum:['meetup','playtest','discussion','workshop','project_meeting']},
      startsAt:{type:'string',format:'date-time'},endsAt:{type:'string',format:'date-time'},capacity:{type:'integer',minimum:2,maximum:200},meetingUrl:{type:['string','null'],maxLength:1000},joinWindowMinutes:{type:'integer',minimum:10,maximum:1440},recording:{type:'boolean'},
      codeOfConduct:{type:'string',minLength:10,maxLength:1000},cancellationPolicy:{type:'string',minLength:10,maxLength:500},projectId:{type:['string','null'],format:'uuid'},workId:{type:['string','null'],format:'uuid'},
    };
    app.get('/v1/community/overview',{preHandler:optionalAuth},async request=>({data:await service.experience.overview(request.actor)}));
    app.get('/v1/community/me/participation',{preHandler:requireAuth},async request=>({data:await service.experience.participation(request.actor)}));
    app.post('/v1/community/me/participation/notifications/:notificationId/read',{preHandler:requireAuth,schema:{params:params('notificationId')}},async request=>({data:await service.experience.read(request.actor,request.params.notificationId)}));
    app.get('/v1/community/events',{preHandler:optionalAuth,schema:{querystring:{type:'object',additionalProperties:false,properties:{scope:{type:'string',enum:['upcoming','past','all']},mine:{type:'boolean'},limit:{type:'integer',minimum:1,maximum:50}}}}},async request=>({data:await service.events.list(request.actor,request.query)}));
    app.post('/v1/community/events',{preHandler:requireAuth,schema:{body:{type:'object',additionalProperties:false,required:['title','summary','eventType','startsAt','endsAt','capacity','codeOfConduct','cancellationPolicy'],properties:eventProperties}}},async(request,reply)=>send(reply,await service.events.create(request.actor,request.body)));
    app.get('/v1/community/events/:eventId',{preHandler:optionalAuth,schema:{params:eventParams}},async(request,reply)=>send(reply,await service.events.get(request.actor,request.params.eventId)));
    app.patch('/v1/community/events/:eventId',{preHandler:requireAuth,schema:{params:eventParams,body:{type:'object',additionalProperties:false,required:['expectedVersion'],properties:{...eventProperties,expectedVersion:{type:'integer',minimum:1},state:{type:'string',enum:['scheduled','cancelled','completed']},recapPostId:{type:['string','null'],format:'uuid'}}}}},async(request,reply)=>send(reply,await service.events.update(request.actor,request.params.eventId,request.body)));
    app.post('/v1/community/events/:eventId/register',{preHandler:requireAuth,schema:{params:eventParams}},async(request,reply)=>send(reply,await service.events.register(request.actor,request.params.eventId)));
    app.post('/v1/community/events/:eventId/unregister',{preHandler:requireAuth,schema:{params:eventParams}},async(request,reply)=>send(reply,await service.events.unregister(request.actor,request.params.eventId)));
    const partyProperties={title:{type:'string',minLength:3,maxLength:100},workId:{type:'string',format:'uuid'},modeId:{type:['string','null'],format:'uuid'},modeLabel:{type:'string',minLength:2,maxLength:80},note:{type:'string',minLength:10,maxLength:500},startsAt:{type:'string',format:'date-time'},capacity:{type:'integer',minimum:2,maximum:8},roomMode:{type:'string',enum:['gamehub','external']},externalInstructions:{type:['string','null'],maxLength:1000}};
    app.get('/v1/community/parties',{preHandler:optionalAuth,schema:{querystring:{type:'object',additionalProperties:false,properties:{mine:{type:'boolean'},limit:{type:'integer',minimum:1,maximum:50}}}}},async request=>({data:await service.parties.list(request.actor,request.query)}));
    app.post('/v1/community/parties',{preHandler:requireAuth,schema:{body:{type:'object',additionalProperties:false,required:['title','workId','modeLabel','note','startsAt','capacity','roomMode'],properties:partyProperties}}},async(request,reply)=>send(reply,await service.parties.create(request.actor,request.body)));
    app.get('/v1/community/parties/:partyId',{preHandler:optionalAuth,schema:{params:partyParams}},async(request,reply)=>send(reply,await service.parties.get(request.actor,request.params.partyId)));
    app.post('/v1/community/parties/:partyId/join',{preHandler:requireAuth,schema:{params:partyParams}},async(request,reply)=>send(reply,await service.parties.join(request.actor,request.params.partyId)));
    app.post('/v1/community/parties/:partyId/leave',{preHandler:requireAuth,schema:{params:partyParams}},async(request,reply)=>send(reply,await service.parties.leave(request.actor,request.params.partyId)));
    app.post('/v1/community/parties/:partyId/ready',{preHandler:requireAuth,schema:{params:partyParams,body:{type:'object',additionalProperties:false,required:['ready'],properties:{ready:{type:'boolean'}}}}},async(request,reply)=>send(reply,await service.parties.ready(request.actor,request.params.partyId,request.body.ready)));
    app.post('/v1/community/parties/:partyId/start',{preHandler:requireAuth,schema:{params:partyParams}},async(request,reply)=>send(reply,await service.parties.start(request.actor,request.params.partyId)));
    app.post('/v1/community/parties/:partyId/finish',{preHandler:requireAuth,schema:{params:partyParams,body:{type:'object',additionalProperties:false,required:['state'],properties:{state:{type:'string',enum:['ended','cancelled']}}}}},async(request,reply)=>send(reply,await service.parties.finish(request.actor,request.params.partyId,request.body.state)));
  }
  app.post('/v1/community/posts/:postId/media',{preHandler:requireAuth,schema:{params:params('postId'),body:{type:'object',additionalProperties:false,required:['bytes','contentType','sha256'],properties:{bytes:{type:'integer',minimum:1,maximum:2097152},contentType:{type:'string',enum:['image/jpeg','image/png','image/webp']},sha256:{type:'string',pattern:'^[a-f0-9]{64}$'}}}}},async request=>({data:await media.reserve(request.actor,request.params.postId,request.body,request.headers['idempotency-key'])}));
  app.put('/v1/community/media/:assetId/content',{preHandler:requireAuth,bodyLimit:2097152,schema:{params:params('assetId')}},async request=>{
    if(!request.body?.[Symbol.asyncIterator])throw new CommunityError('MEDIA_INVALID',400,'需要二进制图片请求。');
    const timer=setTimeout(()=>request.body.destroy(new CommunityError('UPLOAD_TIMEOUT',408,'图片上传超时。')),15000);
    try{return {data:await media.upload(request.actor,request.params.assetId,request.body)};}finally{clearTimeout(timer);}
  });
  app.post('/v1/community/media/:assetId/complete',{preHandler:requireAuth,schema:{params:params('assetId')}},async request=>({data:await media.complete(request.actor,request.params.assetId)}));
  app.get('/v1/community/me/media/:assetId',{preHandler:requireAuth,schema:{params:params('assetId')}},async request=>({data:await media.status(request.actor,request.params.assetId)}));
  app.get('/v1/community/media/:assetId/:variant',{preHandler:optionalAuth,schema:{params:{type:'object',additionalProperties:false,required:['assetId','variant'],properties:{assetId:{type:'string',format:'uuid'},variant:{enum:['thumb','display']}}},querystring:{type:'object',additionalProperties:false,properties:{preview:{type:'boolean'}}}}},async(request,reply)=>{
    const bytes=await media.content(request.actor,request.params.assetId,request.params.variant,{preview:request.query.preview===true});
    return reply.header('X-Content-Type-Options','nosniff').type('image/webp').send(bytes);
  });
}
